= Managing Clusters Using the PHP SDK with Couchbase Server
:navtitle: Managing Clusters
:page-aliases: concept-docs:buckets-and-clusters,concept-docs:collections,howtos:provisioning-cluster-resources

[abstract]
This section covers the convenience functionality in the Couchbase PHP SDK for managing buckets, managing indexes used by N1QL and managing views.

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The PHP SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the PHP SDK may be performed through several interfaces depending on the object.
There are two to consider:

* The [.api]`CouchbaseClusterManager` class (obtained via [.api]`CouchbaseCluster#manager(string $username, string $password)` passing administrative user name and password)
* The [.api]`CouchbaseBucketManager` class (obtained via [.api]`CouchbaseBucket#manager()`).

== Getting Information About the Cluster

When you call `CouchbaseClusterManager#info()` it returns a `mixed` object that contains information on the overall cluster state.

[source,php]
----
$cluster = new CouchbaseCluster('couchbase://localhost');
$manager = $cluster->manager('Administrator', 'password');
$info = $manager->info();
printf("cluster has %d nodes, %d buckets and %d megabytes used\n",
       count($info['nodes']), count($info['buckets']),
       $info['storageTotals']['ram']['usedByData'] / 1024 / 1024);
----

Output:

....
cluster has 1 nodes, 3 buckets and 105 megabytes used
....

== Creating and Removing Buckets

The [.api]`CouchbaseClusterManager` class may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the [.api]``CouchbaseCluster``'s [.api]`manager()` method, providing the administrative user name and password.

----
$cluster = new CouchbaseCluster('couchbase://localhost');
$clusterManager = $cluster->manager('Administrator', 'password');
----

To create a bucket, use the [.api]``CouchbaseClusterManager``'s [.api]`createBucket(string $name, array $opts)` method.
The [.api]`$opts` array is used to provide the configuration of the new bucket, while the string is the name given to the bucket.
These are the default configuration options:

[source,php]
----
array(
  'authType' => 'sasl',
  'bucketType' => 'couchbase',
  'ramQuotaMB' => 100,
  'replicaNumber' => 1
);
----

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Only the [.param]`$name` and [.param]`$opts['bucketType']` parameters are mandatory for configuring a bucket.
This list of parameters is recognized for the [.param]`$opts` array, corresponding to those available in the REST API:

* [.param]`name`: The name of the bucket (actually taken from the [.param]`$name` method parameter, cannot be updated).
* [.param]`bucketType`: The type of the bucket (mandatory to specify one, cannot be changed).
Defaults to `'couchbase'`, but can also be `'memcached'` to create a cache bucket.
* [.param]`ramQuotaMB`: How much memory should each cluster node use for the bucket.
This number is specified in megabytes, defaults to 100MB
* [.param]`saslPassword`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) to specify the [.param]`password` parameter.
Must be used together with [.param]`$opts['authType'] = 'sasl'` (which is the default).
* [.param]`flushEnabled`: Enables the [.api]`+CouchbaseBucketManager->flush()+` operation to be performed on this bucket
// PHP SDK does not implement it yet: (see the <xref href="#managing-cluster-php/flushing"/> section below)
.
* [.param]`replicaNumber`: The number of replicas to use for the bucket, default to 1.
* [.param]`replicaIndex`: Whether or not to replicate indexes.

// TODO: PHP SDK does not have updateBucket() implemented

The following example creates a "hello" bucket.
Note how all parameters are set:

[source,php]
----
$bucketSettings = array(
  'bucketType' => 'couchbase',
  'ramQuotaMB' => 120,
  'saslPassword' => '',
  'flushEnabled' => true,
  'replicaNumber' => 1,
  'replicaIndex' => true
);

$manager = $cluster->manager('Administrator', 'password');
$manager->createBucket('hello', $bucketSettings);
----

Once you no longer need to use the bucket, you may delete the bucket using the [.api]`CouchbaseClusterManager#removeBucket($name)` method:

[source,php]
----
$cluster->removeBucket('hello');
----

== N1QL Index Management

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=index-management]

You can manage indexes in the PHP SDK using the [.api]`CouchbaseBucketManager` class, with its various N1QL related methods: [.api]`listN1qlIndexes()`, [.api]`+createN1qlIndex(...)+`, etc\...

The following example creates a N1QL secondary index named "fullName" on the "test" bucket, indexing fields "firstName" and "lastName" (Boolean flags as the last argument mean do not throw an error if the index with the same name already exists):

[source,php]
----
$cluster = new CouchbaseCluster('couchbase://localhost');
$bucket = $cluster->openBucket("test");
$manager = $bucket->manager();

$manager->createN1qlIndex("fullName", array("firstName", "lastName" ), '`state` = "active"',
                          true, false);
----

== View Management

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the PHP SDK, design documents and view definitions are represented by associative arrays.
All operations on design documents are performed on a `CouchbaseBucketManager` instance.

To inspect design documents, you can either retrieve them by name (`+$bucketManager->getDesignDocument("landmarks");+`) or iterate through an array of documents (`+$bucketManager->getDesignDocuments();+`).

To create or update design documents, use the [.api]`insertDesignDocument($name, $data)` and [.api]`upsertDesignDocument($name, $data)` methods.

The following example inserts design documents with two regular views and one spatial view into a bucket named `travel-sample`:

[source,php]
----
// Initialize design document
$designDoc = array(
    'views' => array(
        'by_country' => array(
            'map' => "function (doc, meta) {
                        if (doc.type == 'landmark') {
                           emit([doc.country, doc.city], null);
                        }
                      }"
        ),
        'by_activity' => array(
            'map' => "function (doc, meta) {
                        if (doc.type == 'landmark') {
                          emit(doc.activity, null);
                        }
                      }",
            'reduce' => "_count"
        )
    )
);

// Insert design document into the bucket, as "landmarks"
$manager->insertDesignDocument('landmarks', $designDoc);

$designDoc = array(
    'spatial' => array(
        'by_coordinates' => "function (doc, meta) {
                               if (doc.type == 'landmark') {
                                 emit([doc.geo.lon, doc.geo.lat], null);
                               }
                             }"
    )
);
$manager->insertDesignDocument('landmarks_spatial', $designDoc);
----

include::6.0@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

[source,php]
----
// Get design document to be updated
$designDoc = $manager->getDesignDocument('landmarks');

// Update the "by_country" view, adding a reduce
$designDoc['views']['by_country'] += array('reduce' => "_count"); //added reduce function

// Resend to server
$bucketManager->upsertDesignDocument($designName, $designDoc);
----

To remove a design document from a bucket, call the `removeDesignDocument` method with the name of the design document.

== Configuration Cache File

The legacy client configuration cache file records the current cluster configuration, which Couchbase Server uses at startup.

Client applications use _libcouchbase_ to connect to Couchbase Server.
By means of libcouchbase, the client can react to changes in cluster-topology.
Whenever the client is started, libcouchbase is instantiated, and checks the local filesystem for a _configuration cache file_, containing information on the cluster-toplogy.
If no such file exists, libcouchbase connects to the cluster by means of a REST method, in order to receive the latest topology details.
Once acquired, these details are written to the configuration cache file, locally.

Subsequently, when starting, the client uses the local configuration cache file to acquire its topology data.
If at any time, when using this data, the client attempts to access a data item on a node, and is informed by Couchbase Server that the node is incorrect (due to the cluster configuration having changed), the current configuration cache file is duly invalidated.
The client then requests an updated set of toplogy details from Couchbase Server; which are themselves then saved locally by the client, as a new configuration cache file.

Use of the configuration cache-file is available only through PHP (not through Java or .NET), Node.js, and Python.
Therefore, to use the cache file, add the following to the `php.ini`:

----
couchbase.config_cache = /tmp
----
