= Install and Start Using the PHP SDK with Couchbase Server
:navtitle: Start Using the SDK
:page-aliases: getting-started,hello-couchbase,php-intro,hello-world:start-using-sdk,concept-docs:http-services
include::partial$attributes.adoc[]

[abstract]
The Couchbase PHP SDK allows you to connect to a Couchbase cluster from PHP.
The Couchbase PHP SDK is a native PHP extension and uses the Couchbase high-performance C library to handle communicating to the cluster over Couchbase binary protocols.
The Couchbase PHP SDK is compatible with both PHP 5.6 and 7.0.

== Installing on Linux

For installation on Linux, install the _couchbase-release_ repository, and then install the _libcouchbase_ packages.
The following examples download and install _couchbase-release_ repository, a C and C++ compiler, the C SDK development files (_libcouchbase-devel_ [RPM] or _libcouchbase-dev_ [DEB]), PHP development files, and finally the PHP SDK using _pecl_.

.Debian and Ubuntu
[source,bash]
----
# Only needed during first-time setup:
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
sudo dpkg -i couchbase-release-1.0-6-amd64.deb
# Will install or upgrade packages
sudo apt-get update
sudo apt-get install libcouchbase-dev build-essential php-dev zlib1g-dev
sudo pecl install couchbase
----

For Ubuntu 18.10, and other Debian based releases unsupported by `couchbase-release-1.0-6-amd64.deb`, either replace the above _first-time setup_ instructions with (here using _cosmic_ for Ubuntu 18.10 Cosmic):

[source,bash]
----
sudo wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
echo "deb http://packages.couchbase.com/ubuntu cosmic cosmic/main" | sudo tee /etc/apt/sources.list.d/couchbase.list
----

or, see the detailed instructions on manually adding repos for your version in the xref:c-sdk::sdk-release-notes.adoc#configuring-apt-repositories-debian-ubuntu[C SDK installation instructions].

[NOTE]
====
On Ubuntu 14.04 (Trusty), and possibly some other distributions, you will need to substitute for _php-dev_ with _php5-dev_.
To find particular variants of php-dev for your Ubuntu or Debian-based distribution, use the command

[source,bash]
----
$ apt-cache search php | grep dev
----
====

.RHEL and CentOS
[source,bash]
----
# Only needed during first-time setup:
wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-x86_64.rpm
sudo rpm -iv couchbase-release-1.0-6-x86_64.rpm
# Will install or upgrade existing packages
sudo yum install libcouchbase-devel gcc gcc-c++ php-devel zlib-devel
sudo pecl install couchbase
----

== Installation on Mac OS X

On MacOS, the `libcouchbase` package is available in https://brew.sh[homebrew/core], and can be installed with:

[source,bash]
----
brew install libcouchbase
----

As `homebrew/php` is no longer available, the current best way to install newer versions of PHP (and one with the necessary permissions) is found at https://php-osx.liip.ch[^].
Download `install.sh` from there or, if you are happy with the script, install in one line (in this example, PHP 7.2) with:

[source,bash]
----
curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2
----

Once you have PHP installed, then use `PECL` to install the Couchbase PHP SDK
(read your PHP distribution manual to find out where `pecl` is located and whether the user needs special permissions to install new extensions):

[source,bash]
----
/path/to/pecl install couchbase
----

== Installing on Microsoft Windows

When using Microsoft Windows, download one of the pre-built binaries at http://developer.couchbase.com/server/other-products/release-notes-archives/php-sdk[Archives^], matching your environment or at http://pecl.php.net/package/couchbase[PECL^].
You also have the option of downloading the https://github.com/couchbaselabs/php-couchbase[source^] for the SDK and building it directly.

== Post Installation - Setting up the php.ini

Once the PHP SDK has been installed, you need to specify that the PHP interpreter should load the Couchbase SDK as an extension.
To do this:

. Locate the location of your php.ini file.
This can be done by `php --ini`
+
[source,bash]
----
$ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php/7.0
Loaded Configuration File:         /usr/local/etc/php/7.0/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.0/conf.d
Additional .ini files parsed:      (none)
----

. Insert the following line in the `php.ini` file; this should be in the `[PHP]` section.
If you don't know where that is, simply search for existing commented or uncommented `extension=` entries in the file.
+
.Linux and Mac OS
----
extension=couchbase.so
----
+
.Windows
----
extension=couchbase.dll
----
+
The Couchbase SDK Version 2.2.4 depends on both the JSON and https://pecl.php.net/package/pcs[PCS (PHP Code Service) extensions^].
Releases from 2.0.0 through 2.2.3 and from 2.3.0 forward depend only on the JSON extension.
Make sure that the load order is correct.
For example, if your distribution has just a single `php.ini` file, just insert the line after `extension=json.so`.
If your distribution uses a `conf.d`-style, name the file with the Couchbase SDK ini so that it will be alphabetically ordered after the JSON extension.
+
IMPORTANT: Because the extension depends on the C library (libcouchbase), the shared object `libcouchbase.so` or `libcouchbase.dll` has to be accessible by the PHP process when loading the extension.
On UNIX-like systems no additional steps are necessary, because the libcouchbase package installs shared objects into a common system location.
For Windows though, it must be copied into either into a location from the `PATH` for the PHP executable or into a directory with like executables (like apache2, IIS or php.exe).
This is controlled by your PHP distribution's setup, so see its documentation for further information.

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:sdk-release-notes.adoc[in the release notes].

== Hello Couchbase

The Hello Couchbase example consists of one PHP file, [.path]_hello-couchbase.php_.
The code opens a connection to Couchbase Server, retrieves a document, modifies the document, and stores the updated document in the database.
The [.path]_hello-couchbase.php_ code is below.
Note that to connect to a Couchbase bucket, you must use Couchbase _Role-Based Access Control_ (RBAC).
This is fully described in the section xref:6.0@server:learn:security/authorization-overview.adoc[Authorization].
A username and password for the current user must be specified.
Following successful authentication, the bucket is opened.

.hello-couchbase.php
[source,php]
----
<?php
$bucketName = "bucket-name";

// Establish username and password for bucket-access
$authenticator = new \Couchbase\PasswordAuthenticator();
$authenticator->username('username')->password('password');

// Connect to Couchbase Server
$cluster = new CouchbaseCluster("couchbase://127.0.0.1");

// Authenticate, then open bucket
$cluster->authenticate($authenticator);
$bucket = $cluster->openBucket($bucketName);

// Store a document
echo "Storing u:king_arthur\n";
$result = $bucket->upsert('u:king_arthur', array(
    "email" => "kingarthur@couchbase.com",
    "interests" => array("African Swallows")
));

var_dump($result);

// Retrieve a document
echo "Getting back u:king_arthur\n";
$result = $bucket->get("u:king_arthur");
var_dump($result->value);

// Replace a document
echo "Replacing u:king_arthur\n";
$doc = $result->value;
array_push($doc->interests, 'PHP 7');
$bucket->replace("u:king_arthur", $doc);
var_dump($result);

echo "Creating primary index\n";
// Before issuing a N1QL Query, ensure that there is
// is actually a primary index.
try {
    // Do not override default name; fail if it already exists, and wait for completion
    $bucket->manager()->createN1qlPrimaryIndex('', false, false);
    echo "Primary index has been created\n";
} catch (CouchbaseException $e) {
    printf("Couldn't create index. Maybe it already exists? (code: %d)\n", $e->getCode());
}

// Query with parameters
$query = CouchbaseN1qlQuery::fromString("SELECT * FROM `$bucketName` WHERE \$p IN interests");
$query->namedParams(array("p" => "African Swallows"));
echo "Parameterized query:\n";
var_dump($query);
$rows = $bucket->query($query);
echo "Results:\n";
var_dump($rows);
----

The console output should look similar to this:

....
Storing u:king_arthur
object(CouchbaseMetaDoc)#4 (5) {
  ["error"]=>
  NULL
  ["value"]=>
  NULL
  ["flags"]=>
  NULL
  ["cas"]=>
  string(10) "eldhjkkzcw"
  ["token"]=>
  NULL
}
Getting back u:king_arthur
object(stdClass)#5 (2) {
  ["email"]=>
  string(24) "kingarthur@couchbase.com"
  ["interests"]=>
  array(1) {
    [0]=>
    string(16) "African Swallows"
  }
}
Replacing u:king_arthur
object(CouchbaseMetaDoc)#6 (5) {
  ["error"]=>
  NULL
  ["value"]=>
  object(stdClass)#5 (2) {
    ["email"]=>
    string(24) "kingarthur@couchbase.com"
    ["interests"]=>
    array(2) {
      [0]=>
      string(16) "African Swallows"
      [1]=>
      string(5) "PHP 7"
    }
  }
  ["flags"]=>
  int(33554438)
  ["cas"]=>
  string(10) "eldhjkkzcw"
  ["token"]=>
  NULL
}
Creating primary index
Primary index has been created
Parameterized query:
object(CouchbaseN1qlQuery)#8 (2) {
  ["options"]=>
  array(2) {
    ["statement"]=>
    string(45) "SELECT * FROM `bucket-name` WHERE $p IN interests"
    ["$p"]=>
    string(16) "African Swallows"
  }
  ["adhoc"]=>
  bool(true)
}
Results:
object(stdClass)#11 (3) {
  ["rows"]=>
  array(1) {
    [0]=>
    object(stdClass)#10 (1) {
      ["bucket-name"]=>
      object(stdClass)#9 (2) {
        ["email"]=>
        string(24) "kingarthur@couchbase.com"
        ["interests"]=>
        array(2) {
          [0]=>
          string(16) "African Swallows"
          [1]=>
          string(5) "PHP 7"
        }
      }
    }
  }
  ["status"]=>
  string(7) "success"
  ["metrics"]=>
  array(4) {
    ["elapsedTime"]=>
    string(11) "11.623318ms"
    ["executionTime"]=>
    string(11) "11.605128ms"
    ["resultCount"]=>
    int(1)
    ["resultSize"]=>
    int(220)
  }
}
....

== API Reference

The API reference is generated for each version.
The API reference for version `{php-current-version}` is at {php-api-link}[]
