= Distributed Transactions from the PHP SDK
:description: Distributed ACID Transactions in Couchbase SDKs
:navtitle: ACID Transactions
:page-topic-type: howto

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=intro]


== Requirements

* Couchbase Server 6.6.1 or above.
* Couchbase PHP SDK 4.0.0 or above.
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured. 
Simply install the most recent version of the SDK.
// You may, on occasion, need to import some enumerations for particular settings, but in basic cases nothing is needed.

== Configuration

Transactions can optionally be globally configured when configuring the `Cluster`.
For example, if you want to change the level of durability which must be attained, this can be configured as part of the connect options:

[source,php]
----
include::example$transactions-example.php[tag=config,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=config]

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,php]
----
include::example$transactions-example.php[tag=create,indent=0]
----

// TODO: this partial may need to be reviewed
// TODO: see https://docs.couchbase.com/java-sdk/current/howtos/distributed-acid-transactions-from-the-sdk.html#:~:text=The%20lambda%20gets%20passed%20an%20AttemptContext%20object%2C%20generally%20referred%20to%20as%20ctx%20here.
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

== Examples

Here is a quick summary of the main transaction operations.
They are described in more detail below. 

[source,php]
----
include::example$transactions-example.php[tag=examples,indent=0]
----

// TODO: this partial references things that are Java implementation specific
//       like a Transactions object
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=mechanics]


== Key-Value Mutations

=== Replacing

// TODO check PHP relevance of following
Replacing a document requires a `ctx.get()` call first.
This is necessary so the transaction can check that the document is not involved in another transaction.
If it is, then the transaction will handle this at the `ctx.replace()` point.
Generally, this involves rolling back what has been done so far, and retrying the lambda.
Handling errors should be done through try/catch as in the example above.

[source,php]
----
include::example$transactions-example.php[tag=replace,indent=0]
----

=== Removing

// TODO check PHP relevance of following
As with replaces, removing a document requires a `ctx.get()` call first.

[source,php]
----
include::example$transactions-example.php[tag=remove,indent=0]
----

=== Inserting

[source,php]
----
include::example$transactions-example.php[tag=insert,indent=0]
----

== Key-Value Reads

From a transaction context you may get a document:

[source,php]
----
include::example$transactions-example.php[tag=get,indent=0]
----

// TODO check PHP relevance of following
`get` will cause the transaction to fail with `TransactionFailed` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check the `Optional` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,php]
----
include::example$transactions-example.php[tag=getReadOwnWrites,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-intro]

=== Using N1QL

If you already use N1QL from the PHP SDK, then its use in transactions is very similar.
it returns the same `QueryResult` you are used to, and takes most of the same options.

// TODO check PHP relevance of following
You must take care to write `ctx.query()` inside the lambda however, rather than `cluster.query()` or `scope.query()`.

An example of SELECTing some rows from the `travel-sample` bucket:

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesSelect,indent=0]
----

Rather than specifying the full "`travel-sample`.inventory.hotel" name each time, it is easier to pass a reference to the inventory `Scope`:

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesSelectScope,indent=0]
----

An example using a `Scope` for an UPDATE:

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesUpdate,indent=0]
----

And an example combining SELECTs and UPDATEs.
It's possible to call regular PHP functions from the lambda, as shown here, permitting complex logic to be performed.
Just remember that since the lambda may be called multiple times, so may the method.

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesComplex,indent=0]
----

=== Read Your Own Writes

As with Key-Value operations, N1QL queries support Read Your Own Writes.

This example shows INSERTing a document and then SELECTing it again.

[source,php]
----
include::example$transactions-example.php[tag=queryInsert,indent=0]
----
<1> The inserted document is only staged at this point. as the transaction has not yet committed.
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the SELECT can, as we are reading a mutation staged inside the same transaction.

=== Mixing Key-Value and N1QL

Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.

In this example we insert a document with Key-Value, and read it with a SELECT.

[source,php]
----
include::example$transactions-example.php[tag=queryRyow,indent=0]
----

<1> As with the 'Read Your Own Writes' example, here the insert is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the SELECT can view it, as the insert was in the same transaction.

=== Query Options

// TODO check PHP relevance of following
Query options can be provided via `TransactionsQueryOptions`, which provides a subset of the options in the PHP SDK's `QueryOptions`.

[source,php]
----
include::example$transactions-example.php[tag=queryOptions,indent=0]
----

// TODO: check this partial to see if it matches up across SDKs.  otherwise, make it a table?
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-options]

// TODO check PHP relevance of following
See the xref:howtos:n1ql-queries-with-sdk.adoc#query-options[QueryOptions documentation] for details on these.

// TODO: Replace the section below with this when we ensure that the shared partials in common are truly generic.
// include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-perf]
=== Query Performance Advice
This section is optional reading, and only for those looking to maximize transactions performance.

After the first query statement in a transaction, subsequent Key-Value operations in the lambda are converted into N1QL and executed by the query service rather than the Key-Value data service.
The operation will behave identically, and this implementation detail can largely be ignored, except for this caveat:

* These converted Key-Value operations are likely to be slightly slower, as the query service is optimised for statements involving multiple documents.
Those looking for the maximum possible performance are recommended to put Key-Value operations before the first query in the lambda, if possible.

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-single]

[source,php]
----
include::example$transactions-example.php[tag=querySingle,indent=0]
----

// TODO check PHP relevance of following
// You can also run a single query transaction against a particular `Scope` (these examples will exclude the full error handling for brevity):
//
// [source,typescript]
// ----
// include::example$transactions-example.ts[tag=querySingleScoped,indent=0]
// ----
//
// and configure it:
//
// [source,typescript]
// ----
// include::example$transactions-example.ts[tag=querySingleConfigured,indent=0]
// ----

== Committing

// TODO check PHP relevance of following
Committing is automatic: if there is no explicit call to `ctx.commit()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.
Committing is automatic at the end of the code block with the transaction context.
If no exception is thrown, it will be committed.
If you want to rollback the transaction, simply throw an exception.
Transactions may rollback from the transaction logic itself, various failure conditions, or from your application logic by throwing an exception.

As soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed - even if the application crashes.


// == A Full Transaction Example
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=example]

// TODO: need to create this
// A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-php-examples[GitHub transactions examples page].

[source,php]
----
include::example$transactions-example.php[tag=full,indent=0]
----

// TODO: this partial has some Java specific things in it
// concurrency
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=concurrency]

// TODO: this is to identify violations of cooperative, not known if this is available in node/cb++
// [source,java]
// ----
// include::example$TransactionsExample.java[tag=concurrency,indent=0]
// ----
//
// These events will be raised in the event of a non-transactional write being detected and overridden.
// The event contains the key of the document involved, to aid the application with debugging.


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

// TODO check PHP relevance of following
// If the transaction is not retried then it will throw an exception, and its `error` contains details on the failure.
// In Typescript, you may branch your error handling based on `instanceof` with one of `TransactionOperationFailedError`, `TransactionFailedError`, `TransactionExpiredError` or `TransactionCommitAmbiguousError`.

The application can use this to signal why it triggered a rollback, as so:

[source,php]
----
include::example$transactions-example.php[tag=rollback-cause,indent=0]
----

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the system will not try to automatically commit it at the end of the code block.


//  Error Handling
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=error]


// TODO: this partial below has a lot of Java specifics in it
//  txnfailed
//include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

//[source,java]
//----
//include::example$TransactionsExample.java[tag=config-expiration,indent=0]
//----

//include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed1]

//Similar to `TransactionResult`, `SingleQueryTransactionResult` also has an `unstagingComplete()` method.

=== Full Error Handling Example

Pulling all of the above together, this is the suggested best practice for error handling:

[source,php]
----
include::example$transactions-example.php[tag=full-error-handling,indent=0]
----

// TODO: this partial below has reference to a Transactions object, which is no longer the case going forward
// include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=cleanup]

=== Monitoring Cleanup

To monitor cleanup, increase the verbosity on the logging.

//TODO: once events are available, re-add the below
//[source,java]
//----
//include::example$TransactionsExample.java[tag=cleanup-events,indent=0]
//----
//
//`TransactionCleanupEndRunEvent` is raised whenever a current 'run' is finished, and contains statistics from the run.
//(A run is typically around every 60 seconds, with default configuration.)
//
//A `TransactionCleanupAttempt` event is raised when an expired transaction was found by this process, and a cleanup attempt was made.
//It contains whether that attempt was successful, along with any logs relevant to the attempt.
//
//In addition, if cleanup fails to cleanup a transaction that is more than two hours past expiry, it will raise the `TransactionCleanupAttempt` event at WARN level (rather than the default DEBUG).
//With most default configurations of the event-bus (see <<Logging>> below), this will cause that event to be logged somewhere visible to the application.
//If there is not a good reason for the cleanup to be failed (such as a downed node that has not yet been failed-over), then the user is encouraged to report the issue.

== Logging

To aid troubleshooting, raise the log level on the SDK.
// TODO: need to add logging details to the error objects
//To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

//[source,java]
//----
//include::example$TransactionsExample.java[tag=logging,indent=0]
//----
//
//A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.
//
//For convenience there is also a config option that will automatically write this programmatic log to the standard Couchbase Java logging configuration inherited from the SDK if a transaction fails.
//This will log all lines of any failed transactions, to `WARN` level:
//[source,java]
//----
//include::example$TransactionsExample.java[tag=config_warn,indent=0]
//----
//

Please see the xref:howtos:collecting-information-and-logging.adoc[PHP SDK logging documentation] for details.

// TODO: re-add this once tracing becomes available
//== Tracing
//
//This telemetry is particularly useful for monitoring performance.
//
//If the underlying Couchbase Java SDK is configured for tracing, then no further work is required: transaction spans will be output automatically.
//See the xref:howtos:observability-tracing.adoc[Couchbase Java SDK Request Tracing documentation] for how to configure this.
//
//=== Parent Spans
//
//While the above is sufficient to use and output transaction spans, the application may wish to indicate that the transaction is part of a larger span -- for instance, a user request.
//It can do this by passing that as a parent span.
//
//If you have an existing OpenTelemetry span you can easily convert it to a Couchbase `RequestSpan` and pass it to the transactions library:
//
//[source,java]
//----
//include::example$TransactionsExample.java[tag=tracing-wrapped,indent=0]
//----

== Concurrent Operations

The API allows operations to be performed concurrently inside a transaction, which can assist performance.
There are two rules the application needs to follow:

* The first mutation must be performed alone, in serial.
This is because the first mutation also triggers the creation of metadata for the transaction.
* All concurrent operations must be allowed to complete fully, so the transaction library can track which operations need to be rolled back in the event of failure.
This means the application must 'swallow' the error, but record that an error occurred, and then at the end of the concurrent operations, if an error occurred, throw an error to cause the transaction to retry.

// TODO: update this for PHP
//These rules are demonstrated here:

//[source,java]
//----
//include::example$TransactionsExample.java[tag=concurrentOps,indent=0]
//----


// TODO: re-enable once custom metadata collections are supported
// include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-1]

//[source,java]
//----
//include::example$TransactionsExample.java[tag=custom-metadata,indent=0]
//----

//include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-2]

// TODO: re-enable when deferred commits are supported
//== Deferred Commits
//
//NOTE: The deferred commit feature is currently in alpha, and the API may change.
//
//Deferred commits allow a transaction to be paused just before the commit point.
//Optionally, everything required to finish the transaction can then be bundled up into a context that may be serialized into a String or byte array, and deserialized elsewhere (for example, in another process).
//The transaction can then be committed, or rolled back.
//
//The intention behind this feature is to allow multiple transactions, potentially spanning multiple databases, to be brought to just before the commit point, and then all committed together.
//
//Here's an example of deferring the initial commit and serializing the transaction:
//
//[source,java]
//----
//include::example$TransactionsExample.java[tag=defer1,indent=0]
//----
//
//And then committing the transaction later:
//
//[source,java]
//----
//include::example$TransactionsExample.java[tag=defer2,indent=0]
//----
//
//Alternatively the transaction can be rolled back:
//
//[source,java]
//----
//include::example$TransactionsExample.java[tag=defer3,indent=0]
//----
//
//The transaction expiry timer (which is configurable) will begin ticking once the transaction starts, and is not paused while the transaction is in a deferred state.


// TODO: this partial points to the java examples repo
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=further]

