= Distributed Transactions from the PHP SDK
:description: Distributed ACID Transactions in Couchbase SDKs
:navtitle: ACID Transactions
:page-topic-type: howto
:page-toclevels: 2
:page-pagination: next

include::project-docs:partial$attributes.adoc[]
include::partial$acid-transactions-attributes.adoc[]

[abstract]
{description}

This guide will show you examples of how to perform multi-document ACID (atomic, consistent, isolated, and durable) database transactions within your application, using the Couchbase PHP SDK.

Refer to the xref:concept-docs:transactions.adoc[Distributed ACID Transactions] concept material for a high-level overview.

== Prerequisites

[{tabs}]
====
Couchbase Capella::
+
--
* Couchbase Capella account.
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:cloud:organizations:organization-projects-overview.adoc[Organizations & Access] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
--

Couchbase Server::
+
--
* Couchbase Server (6.6.1 or above).
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:{version-server}@server:learn:security/roles.adoc[Roles] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
* NTP should be configured so nodes of the Couchbase cluster are in sync with time.
--
====

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]

== Creating a Transaction

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,php]
----
include::example$transactions-example.php[tag=examples,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag={lambda}-ctx]

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating-error]

== Logging

To aid troubleshooting, raise the log level on the SDK.
// TODO: need to add logging details
//To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

//[source,java]
//----
//include::example$TransactionsExample.java[tag=logging,indent=0]
//----
//
//A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.
//
//For convenience there is also a config option that will automatically write this programmatic log to the standard Couchbase Java logging configuration inherited from the SDK if a transaction fails.
//This will log all lines of any failed transactions, to `WARN` level:
//[source,java]
//----
//include::example$TransactionsExample.java[tag=config_warn,indent=0]
//----
//

Please see the xref:howtos:collecting-information-and-logging.adoc[PHP SDK logging documentation] for details.

== Key-Value Operations

You can perform transactional database operations using familiar key-value CRUD methods:

* **C**reate - `insert()`

* **R**ead - `get()`

* **U**pdate - `replace()`

* **D**elete - `remove()`

[IMPORTANT]
====
As mentioned <<{lambda}-ops,previously>>, make sure your application uses the transactional key-value operations inside the {lambda} -- such as `ctx.insert()`, rather than `collection.insert()`.
====

=== Insert

To insert a document within a transaction {lambda}, simply call `ctx.insert()`.

[source,php]
----
include::example$transactions-example.php[tag=insert,indent=0]
----

=== Get

From a transaction context you may get a document:

[source,php]
----
include::example$transactions-example.php[tag=get,indent=0]
----

If the document does not exist, the transaction will fail with a `TransactionFailedException` (after rolling back any changes, of course).

Gets will "Read Your Own Writes", e.g. this will succeed:

[source,php]
----
include::example$transactions-example.php[tag=getReadOwnWrites,indent=0]
----

=== Replace

Replacing a document requires a `$ctx->get()` call first.
This is necessary so the SDK can check that the document is not involved in another transaction, and take appropriate action if so.

[source,php]
----
include::example$transactions-example.php[tag=replace,indent=0]
----

=== Remove

As with replaces, removing a document requires a `$ctx->get()` call first.

[source,php]
----
include::example$transactions-example.php[tag=remove,indent=0]
----

== {sqlpp} Queries

If you already use https://www.couchbase.com/products/n1ql[{sqlpp} (formerly N1QL)], then its use in transactions is very similar.
It returns the same `QueryResult` you are used to, and takes most of the same options.

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional query operations inside the {lambda} -- such as `ctx.query()`, rather than `cluster.query()` or `scope.query()`.
====

Here is an example of selecting some rows from the `travel-sample` bucket:

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesSelect,indent=0]
----

// TODO: Scope reference stuff doesn't seem to work (marked as deprecated?)
// https://github.com/couchbase/couchbase-php-client/blob/4.0.0/Couchbase/TransactionQueryOptions.php#L296-L325
// Rather than specifying the full "`travel-sample`.inventory.hotel" name each time, it is easier to pass a reference to the inventory `Scope`:

// [source,php]
// ----
// include::example$transactions-example.php[tag=queryExamplesSelectScope,indent=0]
// ----

// An example using a `Scope` for an UPDATE:

// [source,php]
// ----
// include::example$transactions-example.php[tag=queryExamplesUpdate,indent=0]
// ----

And an example combining `SELECT` and an `UPDATE`.

[source,php]
----
include::example$transactions-example.php[tag=queryExamplesComplex,indent=0]
----

As you can see from the snippet above, it is possible to call regular PHP functions from the {lambda}, permitting complex logic to be performed.
Just remember that since the {lambda} may be called multiple times, so may the method.

Like key-value operations, queries support "Read Your Own Writes".
This example shows inserting a document and then selecting it again:

[source,php]
----
include::example$transactions-example.php[tag=queryRYOW,indent=0]
----
<1> The inserted document is only staged at this point, as the transaction has not yet committed. +
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the `SELECT` can, as we are reading a mutation staged inside the same transaction.

=== Query Options

Query options can be provided via `TransactionQueryOptions`, which provides a subset of the options in the PHP SDK's `QueryOptions`.

[source,php]
----
include::example$transactions-example.php[tag=queryOptions,indent=0]
----

.Supported Transaction Query Options
|===
| Name | Description

| `positionalParameters(array<string\|int, mixed>)` | Allows to set positional arguments for a parameterized query.
| `namedParameters(array<string\|int, mixed>)` | Allows you to set named arguments for a parameterized query.
| `scanConsistency(string)` | Sets a different scan consistency for this query.
| `clientContextId(string)` | Sets a context ID returned by the service for debugging purposes.
| `scanWaitMilliseconds(int)` | Allows to specify a maximum scan wait time.
| `scanCap(int)` | Specifies a maximum cap on the query scan size.
| `pipelineBatch(int)` | Sets the batch size for the query pipeline.
| `pipelineCap(int)` | Sets the cap for the query pipeline.
| `profile(int)` | Allows you to enable additional query profiling as part of the response.
| `readonly(bool)` | Tells the client and server that this query is readonly.
| `adHoc(bool)` | If set to false will prepare the query and later execute the prepared statement.
| `raw(string)` | Escape hatch to add arguments that are not covered by these options.
|===

== Mixing Key-Value and {sqlpp}

Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.

In this example we insert a document with a key-value operation, and read it with a `SELECT` query.

[source,php]
----
include::example$transactions-example.php[tag=queryKvMix,indent=0]
----

<1> The key-value insert operation is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the `SELECT` can view it, as the insert was in the same transaction.

== Configuration

Transactions can optionally be globally configured when configuring the `Cluster`.
For example, if you want to change the level of durability which must be attained, this can be configured as part of the connect options:

[source,php]
----
include::example$transactions-example.php[tag=config,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=config]

== Additional Resources

* Learn more about xref:concept-docs:transactions.adoc[Distributed ACID Transactions].

* Check out the SDK https://docs.couchbase.com/sdk-api/couchbase-php-client/namespaces/couchbase.html[API Reference].
