= Search
:description: You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.
:page-topic-type: howto
:page-pagination: full

[abstract]
{description}


Full Text Search or FTS allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase
buckets. It uses natural language processing for querying documents, provides relevance scoring on the results of your
queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and
Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.

The PHP SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying
REST API.

There are two APIs for querying search: `cluster.searchQuery()`, and `cluster.search()`.
Both are also available at the Scope level.

The former API supports FTS queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.

We will perform an FTS query here - see the <<vector search>> section for examples of that.

== Examples

For the purposes of the below examples we will use the Travel Sample sample bucket with the below Full Text Search index
(dynamic mapping for type `hotel`).

[source,json]
----
include::example$search.php[tag=indexdefinition]
----

Search queries are executed at Cluster level (not bucket or collection). As of Couchbase Server 6.5+ they do also not
require a bucket to be opened first.  In older versions of Couchbase Server, even though executed at Cluster level, a
bucket must be opened before performing queries.

Here is a simple MatchQuery that looks for the text “swanky” using a defined index:

[source,php]
----
include::example$search.php[tag=matchquery]
----

All simple query types are created in the same manner, although some have additional properties, which can be seen in
common query type descriptions.  Couchbase FTS's xref:7.1@server:fts:fts-query-types.adoc[range of query types] enable
powerful searching using multiple options, to ensure results are just within the range wanted.  Here is a numeric range
query that looks for hotels with `"Cleanliness"` ratings higher than `5`:

[source,php]
----
include::example$search.php[tag=numrangequery]
----

Queries can also be combined together.
A conjunction query contains multiple child queries; its result documents must satisfy all of the child queries:

[source,php]
----
include::example$search.php[tag=conjunctionquery]
----

== Working with Results

The result of a search query has three components: rows, facets, and metdata.  Rows are the documents that match the
query.  Facets allow the aggregation of information collected on a particular result set.  Metdata holds additional
information not directly related to your query, such as success total hits and how long the query took to execute in the
cluster.

=== Iterating Rows
Here we are iterating over the rows that were returned in the results (for context, see the same in the two samples below this one):

[source,php]
----
foreach ($res->rows() as $row) {
    printf("id: %s, score: %f\n", $row['id'], $row['score']);
}
----

=== Facets

Facets can only be accessed once `Close` has been called on rows.

[source,php]
----
include::example$search-facets.php[tag=iteratingfacets]
----


== Scoped vs Global Indexes
The FTS APIs exist at both the `Cluster` and `Scope` levels.

This is because FTS supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.searchQuery()` / `Scope.search()` for scoped indexes.


== Vector Search
As of Couchbase Server 7.6, the FTS service supports vector search in additional to traditional full text search queries.
// todo link to the server docs when available

=== Examples
==== Single vector query
In this first example we are performing a single vector query:
[source,php]
----
include::example$search.php[tag=singlevectorquery]
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional FTS query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `float[]`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the FTS index "vector-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.search()`.
If it was a global index we would use `cluster.search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

==== Multiple vector queries
You can run multiple vector queries together:

[source,php]
----
include::example$search.php[tag=multiplevectorqueries]
----

How the results are combined (ANDed or ORed) can be controlled with `vectorQueryCombination()` in VectorSearchOptions.

==== Combining FTS and vector queries
You can combine a traditional FTS query with vector queries:

[source,php]
----
include::example$search.php[tag=combinedvectorquery]
----

==== FTS queries
And note that traditional FTS queries, without vector search, are also supported with the new `cluster.search()` / `scope.search()` APIs:

[source,php]
----
include::example$search.php[tag=traditionalftsquery]
----

The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the Couchbase Query Service, FTS allows `RequestPlus` queries -- _Read-Your-Own_Writes (RYOW)_ consistency,
ensuring results contain information from updated indexes:

[source,php]
----
include::example$search.php[tag=consistency]
----


== Further Reading

* More details on Search Queries can be found xref:7.1@server:fts:fts-query-types.adoc[in the Server docs].
* More information can be found in the API docs for 
https://docs.couchbase.com/sdk-api/couchbase-php-client/classes/Couchbase-Cluster.html#method_searchQuery[searchQuery^] and 
https://docs.couchbase.com/sdk-api/couchbase-php-client/classes/Couchbase-SearchResult.html[SearchResult^].


