= Full Text Search from the SDK

[abstract]
You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.


Full Text Search or FTS allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase
buckets. It uses natural language processing for querying documents, provides relevance scoring on the results of your
queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and
Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.

The PHP SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying
REST API.

NOTE: When using a Couchbase version < 6.5 you must create a valid Bucket connection using `$cluster->bucket($name)`
before you can use Search.

== Examples

For the purposes of the below examples we will use the Travel Sample sample bucket with the below Full Text Search index
(dynamic mapping for type `hotel`).

[source,json]
----
include::example$search.php[tag=indexdefinition]
----

Search queries are executed at Cluster level (not bucket or collection). As of Couchbase Server 6.5+ they do also not
require a bucket to be opened first.  In older versions of Couchbase Server, even though executed at Cluster level, a
bucket must be opened before performing queries.

Here is a simple MatchQuery that looks for the text “swanky” using a defined index:

[source,php]
----
include::example$search.php[tag=matchquery]
----

All simple query types are created in the same manner, although some have additional properties, which can be seen in
common query type descriptions.  Couchbase FTS's xref:6.5@server:fts:fts-query-types.adoc[range of query types] enable
powerful searching using multiple options, to ensure results are just within the range wanted.  Here is a numeric range
query that looks for hotels with `"Cleanliness"` ratings higher than `5`:

[source,php]
----
include::example$search.php[tag=numrangequery]
----

Queries can also be combined together.
A conjunction query contains multiple child queries; its result documents must satisfy all of the child queries:

[source,php]
----
include::example$search.php[tag=conjunctionquery]
----

== Working with Results

The result of a search query has three components: rows, facets, and metdata.  Rows are the documents that match the
query.  Facets allow the aggregation of information collected on a particular result set.  Metdata holds additional
information not directly related to your query, such as success total hits and how long the query took to execute in the
cluster.

.Iterating Rows
Here we are iterating over the rows that were returned in the results.

[source,php]
----
include::example$search.php[tag=iterating]
----

.Facets
Facets can only be accessed once `Close` has been called on rows.

[source,php]
----
include::example$search-facets.php[tag=iteratingfacets]
----


== Consistency

Like the Couchbase Query Service, FTS allows `RequestPlus` queries -- _Read-Your-Own_Writes (RYOW)_ consistency,
ensuring results contain information from updated indexes:

[source,php]
----
include::example$search.php[tag=consistency]
----
