= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: document-operations.adoc

include::partial$beta-warning.adoc[]

////
The complete code sample used on this page can be downloaded from
//  xref::example$document.cs[here]
- from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.
////

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref::concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the PHP SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

[source,php]
----
// Insert
$document = ["foo" => "bar", "bar" => "foo"];
$result = $collection->insert("document-key", $document);
----

Options may be added to operations:

[source,php]
----
// Insert (with options)
$document = ["foo" => "bar", "bar" => "foo"];
$options = new \Couchbase\InsertOptions();
$options->expiration(30) // 30 seconds
	->timeout(5000); // 5 seconds
$result = $collection->insert("document-key", $document, $options);
----

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

_Timeout_ is an optional parameter which in the .NET SDK has a type value of `TimeSpan`.
Timeout sets the timeout value for the underlying network connection.
We will add to these options for the _Replace_ example:

[source,php]
----
$document = ["foo" => "bar", "bar" => "foo"];
$options = new \Couchbase\ReplaceOptions();
$options->cas("AADQjvAwoxU=")
        ->expiration(60) // 1 minute
	->timeout(5000); // 5 seconds
$result = $collection->replace("document-key", $document, $options);
----

Expiration sets an explicit time to live (TTL) for a document, for which you can also xref:sdk-xattr-example.adoc[see a more detailed example of TTL discovery] later in the docs.
We'll discuss modifying `Expiration` in more details xref:#net-modifying-expiration[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the
xref:6.5@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,php]
----
$document = ["foo" => "bar", "bar" => "foo"];
$options = new \Couchbase\UpsertOptions();
$options->cas("AADQjvAwoxU=")
        ->expiration(60) // 1 minute
	->timeout(5000); // 5 seconds
$result = $collection->upsert("document-key", $document, $options);
----

// TODO: old-style durability will come later

Here, we have added _Durability_ options, namely `PersistTo` and `ReplicateTo`.
In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:2.6@php-sdk::durability.adoc[6.0 Durability documentation] -- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist.
Couchbase Data Platform 6.5 refines these two options, with xref:concept-docs:durability-replication-failure-considerations.adoc[Synchronous Replication] -- although they remain essentially the same in use.


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Docunent Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,php]
----
$result = $collection->get("document-key");
$content = $result->content();
----

Timeout can also be set - as in the earlier `Insert` example:

[source,php]
----
// Get (with options)
$options = new \Couchbase\GetOptions();
$options->timeout(5000); // 5 seconds
$result = $collection->get("document-key", $options);
$content = $result->content();
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

Remove (with options)
[source,php]
----
$options = new \Couchbase\RemoveOptions();
$options->cas("AAArulMxoxU=")
	->timeout(5000); // 5 seconds
$result = $collection->remove("document-key");
----
// TODO: old-style durability will come later

== Expiration / TTL

By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents.
Using `Touch()`, you can set expiration values on documents to handle transient data:

[source,php]
----
$result = $collection->touch("document-key", 10); // seconds
----

A network timeout can be set with the optional `TouchOptions()`, in the same fashion as earlier examples on this page:

[source,php]
----
$options = new \Couchbase\TouchOptions();
$options->timeout(5000); // 5 seconds
$result = $collection->touch("document-key", 10, $options);
----

== Atomic document modifications

The value of a document can be increased or decreased atomically using `Binary.Increment()` and `.Binary.Decrement()`.

.Increment
[source,php]
----
// increment binary value by 1 (default)
$result = $collection->increment("document-key");
----
// TODO: increment will be extracted into ->binary() interface

[source,php]
----
// increment (with options)
// increment binary value by 1, if document doesn’t exist, seed it at 1000
$options = new \Couchbase\CounterOptions();
$options->delta(1)
        ->initial(1000)
        ->timeout(5000); // 5 seconds
$result = $collection->increment("document-key", $options);
----

.Decrement
[source,php]
----
// decrement binary value by 1
$result = $collection->decrement("document-key");
----

.Decrement (with options)
[source,php]
----
// decrement binary value by 1, if document doesn’t exist, seed it at 1000
// optional arguments:
// - Timeout
// - Expiration
$options = new \Couchbase\CounterOptions();
$options->delta(1)
        ->initial(1000)
        ->timeout(5000); // 5 seconds
$result = $collection->decrement("document-key", $options);
----

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

// For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
