= Query
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.
:page-topic-type: howto
:page-aliases: n1ql-query
:page-pagination: full

[abstract]
{description}
Querying can solve typical programming tasks such as finding a user profile by email address, facebook login, or user ID.



Our query service uses {sqlpp} (formerly N1QL), which will be fairly familiar to anyone who's used any dialect of SQL.
xref:#additional_resources[Further resources] for learning about {sqlpp} are listed at the bottom of the page.
Before you get started you may wish to checkout the xref:7.1@server:n1ql:n1ql-language-reference/index.adoc[{sqlpp} intro page], or just dive in with a query against our travel sample data set.
In this case, the one thing that you need to know is that in order to make a Bucket queryable, it must have at least one index defined.
You can define a _primary_ index on a bucket.
When a primary index is defined you can issue non-covered queries on the bucket as well.

Use
xref:7.1@server::tools/cbq-shell.html[cbq], our interactive Query shell.
Open it, and enter the following:

[source,n1ql]
----
CREATE PRIMARY INDEX ON `travel-sample`
----

or replace _travel-sample_ with a different Bucket name to build an index on a different dataset.

NOTE: The default installation places cbq in `/opt/couchbase/bin/` on Linux, `/Applications/Couchbase Server.app/Contents/Resources/couchbase-core/bin/cbq` on OS X, and `C:\Program Files\Couchbase\Server\bin\cbq.exe` on Microsoft Windows.


== Queries & Placeholders

Placeholders allow you to specify variable constraints for an otherwise constant query.
There are two variants of placeholders: postional and named parameters.
Positional parameters use an ordinal placeholder for substitution and named parameters use variables.
A named or positional parameter is a placeholder for a value in the WHERE, LIMIT or OFFSET clause of a query.
Note that both parameters and options are optional.

.Positional parameter example:
[source,php]
----
include::example$query.php[tag=positionalParams]
----

.Named parameter example:
[source,php]
----
include::example$query.php[tag=namedParams]
----

The complete code for this page's examples can be found https://github.com/couchbase/docs-sdk-php/blob/release/3.2/modules/howtos/examples/query.php:[here]


== Handling Results

In most cases your query will return more than one result, and you may be looking to iterate over those results:

[source,php]
----
include::example$query.php[tag=results]
----

You can also get metrics for your query.
See the https://docs.couchbase.com/sdk-api/couchbase-php-client-3.2.2/classes/Couchbase-QueryMetaData.html#method_metrics[QueryMetaData API docs] for further details.

[source,php]
----
include::example$query.php[tag=metrics]
----

== Scan Consistency


Setting a staleness parameter for queries, with `scan_consistency`, enables a tradeoff between latency and (eventual) consistency.

* A {sqlpp} query using the default *Not Bounded* Scan Consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

* With Scan Consistency set to *RequestPlus*, all document changes and index updates are processed before the query is run.
Select this when consistency is always more important than performance.

* For a middle ground, *AtPlus* is a "read your own write" (RYOW) option, which means it just waits for the new documents that you specify to be indexed, rather than an entire index of multiple documents.
// See the xref:scan-consistency-examples.adoc[examples] for how to use *AtPlus* for the best performance balance for many circumstances.

.ScanConsisteny (RYOW)

[source,php]
----
include::example$query.php[tag=scan]
----

// Due to https://issues.couchbase.com/browse/MB-46876 this section won’t work with named scopes and collections,
// we need to omit this information until Couchbase Server 7.0.1 is available, which will contain the fix for this bug.
// We should avoid showing the user this information until then.
////
More granular consistency requirement could be achieved with `consistentWith` query option, which accepts
`MutationState` object that contains mutations the system must wait for before process the query

[source,php]
----
include::example$query.php[tag=consistentWith]
----
////

== Querying at Scope Level

It is possible to query off the xref:7.1@server:learn:data/scopes-and-collections.adoc[`Scope` level] _as of Couchbase Server release 7.0 onwards_,
using the `query()` method.
It takes the statement as a required argument, and then allows additional options if needed.

A complete list of `QueryOptions` can be found in the https://docs.couchbase.com/sdk-api/couchbase-php-client/classes/Couchbase-QueryOptions.html[API docs].

[source,php]
----
include::example$query.php[tag=scope-level-query]
----

== Additional Resources

NOTE: {sqlpp} is not the only query option in Couchbase.
Be sure to check that your use case fits your selection of query service.

// For a deeper dive into {sqlpp} from the SDK, refer to our xref:[{sqlpp} SDK concept doc].

The xref:7.1@server:n1ql:n1ql-language-reference/index.adoc[Server doc {sqlpp} intro] introduces up a complete guide to the {sqlpp} language, including all of the latest additions.

The http://query.pub.couchbase.com/tutorial/#1[{sqlpp} interactive tutorial] is a good introduction to the basics of {sqlpp} use.

// Indexes / GSI links?

// SQL++ / Analytics.
