= Authenticating against Couchbase Server
:description: As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,php]
----
include::example$auth.php[tag=auth1,indent=0]
----

include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating a PHP Client by Certificate

For sample procedures whereby certificates can be generated and deployed, see xref:6.5@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed:

[source,php]
----
include::example$auth.php[tag=auth2,indent=0]
----

Note the options passed into the connection string:

* `truststorepath` specifies the path (on the local filesystem) to the server's SSL certificate truststore. 
The trust store is optional, and when missing, the library will use `certpath` as the location for verification, and expect any extra certificates to be concatenated in there.

* `certpath` specifies the path (on the local filesystem) to the server's SSL certificate.

* `keypath` specifies the path (on the local filesystem) to the client SSL private key.


include::{version-common}@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,php]
----
include::example$auth.php[tag=auth3,indent=0]
----
