= Transcoders & Non-JSON Documents
:nav-title: Using Transcoders
:page-topic-type: howtos

Information on transcoders can be found in the https://docs.couchbase.com/sdk-api/couchbase-php-client/classes/Couchbase-Bucket.html#method_setTranscoder[API documentation].


[abstract]
The PHP SDK supports common JSON document requirements out-of-the-box.
Custom transcoders provide support for applications needing to perform advanced operations, including supporting non-JSON data.

The PHP SDK uses the concept of encoder and decoder functions, which are used whenever data is sent to or retrieved from Couchbase Server.

When sending data to Couchbase, the SDK passes the Object being sent to a `encoder`.
The `encoder` can either reject the Object as being unsupported, or convert it into an array of bytes and a Common Flag.
The Common Flag specifies whether the data is JSON, a non-JSON string, or raw binary data.

On retrieving data from Couchbase, the fetched bytes and Common Flag are passed to a `decoder`.
The transcoder converts the bytes into a concrete class (the application specifies the required type) if possible.

NOTE: Many applications will not need to be aware of `encoders` and `decoders`, as the defaults support most standard JSON use cases.
The information in this page is only needed if the application has an advanced use-case, likely involving either non-JSON data, or a requirement for a particular JSON serialization library.

== Default Behaviour
`\Couchbase\defaultEncoder` uses the `json_encode` function for serializing byte arrays from concrete objects.
`\Couchbase\defaultDecoder` uses the `json_decode` function for deserializing byte arrays to concrete objects.

On sending data to Couchbase, the encoder function will send Objects to its serializer to convert into a byte array.
The serialized bytes are then sent to the Couchbase Server, along with a Common Flag of JSON.

On retrieving data from Couchbase, the decoder function passes the fetched byte array and Common Flag to its serializer to convert into a concrete class.

This table summarizes that information, and this more concise form will be used to describe the other transcoders included in the SDK.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|string
|Results of serializer
|JSON

|Other
|Results of serializer
|JSON
|===

== PassThruTranscoder
The `\Couchbase\passThruEncoder` allows data to be sent "as is" to the server, applying no serialization.
The corresponding `\Couchbase\passThruDecoder` allows data to be read "as is" from the server, applying no serialization.
This can be used for reading and writing binary string data which should not have JSON serialization applied.
If data is provider to the `passThruEncoder` which is not string data then encoding will fail.

[cols="3", options="header"]
|===
|Item
|Result
|Common Flag

|string
|Raw value
|None

|Other
|Raw value
|None
|===


== Custom Transcoders
More advanced transcoding needs can be accomplished if the application implements their own encoders and decoders.

=== Creating a Custom Transcoder
Let’s look at a more complex example: storing an image.
The encoder function that we will create will be able to handle both image and JSON data allowing it to be used with more than just images.
When we store data with this encoder we will use our own custom Common Flags, so the data will not be compatible with other encoder/decoder functions unless they also recognise these custom flags.

First we will create the encoder function:

[source,php]
----
include::example$transcoding.php[tag=encoder,indent=0]
----

And now create a corresponding decoder function:

[source,php]
----
include::example$transcoding.php[tag=decoder,indent=0]
----

To use these functions with some data we can do the following and our image will be seamlessly stored in Couchbase Server:

[source,php]
----
include::example$transcoding.php[tag=usage,indent=0]
----

== Configuration
Configuring transcoders can be done in multiple ways.

=== INI file
Configuration via the ini file is done using the key `couchbase.encoder.format`.
The values allowed are:
    * json - will use the `\Couchbase\defaultEncoder` and `\Couchbase\defaultDecoder`
    * php - will use the `\Couchbase\passThruEncoder` and `\Couchbase\passThruDecoder`

An additional field of `couchbase.decoder.json_arrays` is also available for use with the `\Couchbase\defaultDecoder`.
This field specifies how JSON objects are decoded by `json_decode`:

[source,php]
----
php > var_dump(json_decode('{"foo": 42}'));
php shell code:1:
class stdClass#1 (1) {
  public $foo =>
  int(42)
}
php > var_dump(json_decode('{"foo": 42}', true));
php shell code:1:
array(1) {
  'foo' =>
  int(42)
}
----

=== Bucket
The `encoder`/`decoder` function pair can be set on the `bucket` to apply to all bucket level operations.

[source,php]
----
bucket->setTranscoder('\Couchbase\defaultEncoder', '\Couchbase\defaultDecoder')
----

=== Operation level
Many operations also support specifying an encoder or decoder at the operation level.

[source,php]
----
$options = new UpsertOptions();
$options->encoder('example_encoder'); // Could be any callable.
$collection->upsert('mydoc', $data, $options);

$options = new GetOptions();
$options->decoder('example_decoder'); // Could be any callable.
$image_doc = $collection->get('mydoc', $options);
----

== Further reading

* For _Common flags_, setting the data format used, see the xref:ref:data-structures.adoc#common-flags[Data Structures reference].
* _Format flags_ for ancient SDKs are still available for compatibility, if you are porting a long-lived legacy app. 
See the xref:ref:data-structures.adoc#legacy-formats[Legacy formats reference].
* If you want to work with binary documents and our Search service, you might like to take a look at https://github.com/khanium/couchbase-fts-binary



