= Compatibility
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2
:page-topic-type: reference

include::partial$attributes.adoc[]

[abstract]
{description}

include::partial$supported-versions.adoc[]

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the PHP SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="30,20,25,30"]
|===
| | SDK 2.6  | SDK 3.0, 3.1 | SDK 3.2, 4.0, 4.1

| *Server 6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0*
| *◎*
| *✔*
| *✔*

| *Server 7.1*
| *◎*
| *◎*
| *✔*

| *Server 7.2*
| *◎*
| *◎*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


=== Capella Compatibility

The Couchbase PHP SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the PHP SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]



== Platform Compatibility

The PHP SDK is tested and supported on the following platforms:


****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8 -- but see note below;
* CentOS 7 & 8 -- but see note below.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux (since PHP SDK 3.1.2) -- see xref:sdk-full-installation.adoc#alpine-linux[installation].

Note, for stability reasons, CentOS and Red Hat ship with far older versions of PHP and GCC than the ones needed to run the latest PHP SDK.
See the xref:project-docs:sdk-full-installation.adoc[full installation page] for details of using the EPEL repo, and other workarounds.

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (October 2022): 13 (Ventura), 12 (Monterey), and 11 (Big Sur).
M1 ARM  architecture is fully supported in the PHP SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 4.1).


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells] 
[cols="7,6,5"]
|===
| | Server 6.6 | Server 7.0 & 7.1

| Enhanced Durability
2+| All SDK versions

| Durable Writes 
2+| Since 3.0

| Analytics
2+| Since 2.6

| Default Collections
| Developer Preview in 6.6, SDK 3.0
| Since 3.0.5footnote:[With C SDK 3.0.7; since PHP SDK 3.1.0 with C SDK 3.1.3.]

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
| Not Supported
| Since SDK 3.2.0

| Request Tracing
2+| Since SDK 3.2.0
|===

include::{version-common}@sdk:shared:partial$network-requirements.adoc[]


include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
