= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:


[abstract]
{description}

include::partial$supported-versions.adoc[]


== Platform Compatibility




=== PHP Version Compatibility

The Couchbase PHP SDK aims to support https://www.php.net/supported-versions.php[all supported versions] of PHP.
The table below indicates the PHP SDK version where support of a version of PHP was added.
PHP versions that have reached their https://www.php.net/eol.php[End-of-Life date] are not supported.

.Supported PHP Versions
[cols="5,8,8"]
|===
| PHP Version | Security Support EOL | Couchbase SDK Versions Supported

| 8.2
| until 2026-12-31
| from 4.1.0

| 8.3
| until 2027-12-31
| from 4.1.6

| 8.4
| until 2028-12-31
| from 4.2.5

| 8.5
| until 2029-12-31
| from 4.5.0
|===


=== OS Compatibility

In general, the SDK can be expected to run on all of the Operating Systems supported by xref:{version-server}@server:install:install-platforms.adoc[Couchbase Server].

However, the {name-sdk} is tested and supported specifically on the following OSs and platforms:

****

The {name-sdk} will run on, and is supported on, the following OSs and platforms.
The SDK has been tested on a representative subset of the platforms listed below.

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8, 9, & 10.
* Oracle Linux 8, 9, & 10.

* Ubuntu (LTS) 22.04 (_Jammy_) & 24.04 (_Noble_).
* Debian 11 (_Bullseye_), Debian 12 (_Bookworm_), & Debian 13 (_Trixie_).
* SUSE Enterprise Linux 12 & 15.
* Alpine Linux 3.21 - 3.23.


[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019, 2022, & 2025.

[discrete]
=== Mac OS X

* The current and previous two releases of OS X.
At time of writing (March 2026): 26 (Tahoe), 15 (Sequoia), and 14 (Sonoma).

[discrete]
=== x86-32 Processor Not Supported

Use of the PHP SDK on legacy or embedded 32-bit platforms is not supported.

While the SDK can be compiled for 32-bit version of x86 platform, there are complications in use from working around number handling in the API, including use of unsigned integers, 
and it is not generally tested and supported.
****




// Platforms, Chipsets, and Virtual Environments.
include::{version-common}@sdk:shared:partial$platform.adoc[tag=virtual]





// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]



== Couchbase Server Compatibility

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.


=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the PHP SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 4.1 - 4.2 | 4.3 | 4.4

| *Server 7.0 - 7.2*
| *✔*
| *✔*
| *✔*

| *Server 7.6* ①
| *✔*
| *✔*
| *✔*

| *Server 8.0* ①
| *✔*
| *✔*
| *✔*
|===

① Server 7.6 & 8.0 are compatible with all supported (not yet End-of-Life) versions of the {name-sdk}, but for full support of the latest features you need to upgrade to a recent version of the SDK.
See the <<#couchbase-new-feature-availability-matrix,Feature Availablity matrix below>> and the xref:sdk-release-notes.adoc[Release Notes page].


Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


=== Capella Compatibility

The Couchbase Ruby SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.0 & 7.1 | Server 7.2 | Server 7.6

| Enhanced Durability
3+| All SDK versions

| Durable Writes
3+| Since 3.0

| Analytics
3+| Since 2.6

| Collections
3+| Since 3.0.5

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
3+| Since SDK 3.2.0

| Request Tracing
3+| Since SDK 3.2.0

| Distributed ACID Transactions
3+| Since SDK 4.0.0

| Cloud Native Gateway
3+| Not Yet Supported

| Vector Search
2+| N/A
| From SDK 4.2.0
|===





=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]




== SDK API Stability


include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
