= Migrating from SDK API 2 to SDK API 3
:description: The SDK API 3 (used in PHP SDK 3.x and 4.x) introduces breaking changes to the previous SDK API 2 APIs (used in PHP SDK 2.x) in order to provide a number of improvements. \
Collections and Scopes are introduced.
:nav-title: Migrating to SDK API 3.x
:page-topic-type: concept
:page-aliases: ROOT:migrate

include::partial$attributes.adoc[]

[abstract]
{description}
The Document class and structure has been completely removed from the API, and the returned value is now `Result`.
Retry behaviour is more proactive, and lazy bootstrapping moves all error handling to a single place.

The current PHP SDK 4.0 is also based on the xref:project-docs:compatibility.adoc#sdk3.2[SDK API 3.2 specification], and offers an entirely new backend (couchbase++) with better support for upcoming features like Distributed ACID Transactions.
We have increased the major version to reflect the importance of this implementation change as per https://semver.org/[semantic versioning].

The intent of this migration guide is to provide detail information on the changes and what to look for while upgrading the SDK.

NOTE: if you are an existing PHP SDK 3._x_ user considering migrating to SDK 4.0,
you may wish to skip to the <<sdk4-specifics,SDK 4.0 specifics>> below.

include::{version-server}@sdk:shared:partial$api-version.adoc[tag=api-version]

// include::{version-server}@sdk:shared:partial$migration.adoc[tag=intro]
// tag::intro[]

== Fundamentals

Before this guide dives into the language-specific technical component of the migration, it is important to understand the high level changes first.
As a migration guide, this document assumes you are familiar with the previous generation of the SDK and does not re-introduce SDK API 2 concepts.
We recommend familiarizing yourself with the new SDK first by reading at least the xref:hello-world:start-using-sdk.adoc[getting started guide], and browsing through the other chapters a little.

// end::intro[]


include::7.1@sdk:shared:partial$migration.adoc[tag=terms]

As an example here is a KeyValue document fetch:

[source,php]
----
$getResult = $collection->get("key", (new GetOptionsl())->timeout(3000000));
----

Compare this to a N1QL query:

[source,php]
----
$queryResult = $cluster->query("select 1=1", (new QueryOptions())->timeout(3000000));
----

include::7.1@sdk:shared:partial$migration.adoc[tag=terms2]


include::7.1@sdk:shared:partial$migration.adoc[tag=new]


include::7.1@sdk:shared:partial$migration.adoc[tag=lang]



// Outline below for individual SDKs -- please expand as appropriate, many topics can be covered lightly
//
// Please use before(2.n) / after (3.0) snippets in all cases where it is helpful
// (probably nearly everywhere, I'm afraid)


===  Installation and Configuration

The primary source of artifacts is xref:installation.adoc[the installation page], 
where we publish links to pre-built binaries, as well as to source tarballs.

From 3.0 onwards, binaries are available for Windows with the OpenSSL dependency. 
Note, that OpenSSL DLLs are not distributed in the archive and must be installed separately (see the https://wiki.openssl.org/index.php/Binaries[official OpenSSL page] for more details).

===  Connection Lifecycle

Bootstrapping the SDK is staged now, so the application has to create a Cluster object first, and then open the Bucket and
Collection if necessary.

As in SDK API 2.x there is no explicit shutdown, and all underlying connections still kept in the cache, for reusing in
future requests. 
The connection idle time is controlled by the `couchbase.pool.max_idle_time_sec` PHP INI setting.

SDK API 3.x allows the performance of Queries on the Cluster level, so it is not necessary to open a bucket anymore.

SDK API 3.x does not allow the use of SASL PLAIN mechanism by default, instead it restricts to `SCRAM-SHA{1,256,512}`.

===  Exception Handling

SDK API 3.x actively uses `Exceptions` to signal errors. 
Instead of using single `\Couchbase\Exception`, as in SDK API 2.x, now we use a hierarchy of exceptions, which allows the handling of errors in a more reliable way:

[source,php]
----
try {
  $collection->get("foo");
} catch (\Couchbase\KeyNotFoundException $ex) {
  $collection->upsert("foo", ["bar" => 42]);
}
----

Instead of SDK API 2's:

[source,php]
----
try {
  $bucket->get("foo");
} catch (\Couchbase\Exception $ex) {
  if ($ex->getCode() == COUCHBASE_KEYNOTFOUND) {
    $bucket->upsert("foo", ["bar" => 42]);
  }
}
----

=== Serialization and Transcoding

SDK API 3.x still relies on native types and supports the `json_encode` API from the standard `json.so` module (therefore it still has to be loaded before `couchbase.so`). 
But the `igbinary.so` transcoder is no longer supported.

NOTE: The `json` module is a core extension from PHP 8.0.0.

===  Migrating Services

==== Key Value

Most of the KV APIs have moved from bucket-level (in SDK API 2.x) to collection-level (in SDK API 3.x). 
For servers which don't support collections, the application should obtain the default collection using the `bucket\->defaultCollection()` function.

The following table describes the mappings from SDK API 2 KV to those of SDK API 3:

.KV changes
[options="header"]
|====
| SDK API 2                       | SDK API 3
|`Bucket\->upsert`                | `Collection\->upsert`
|`Bucket\->get`                   | `Collection\->get`
|-                                | `Collection\->exists`
|`Bucket\->getFromReplica`        | `Collection\->getAnyReplica` and `Collection.getAllReplicas`
|`Bucket\->getAndLock`            | `Collection\->getAndLock`
|`Bucket\->getAndTouch`           | `Collection\->getAndTouch`
|`Bucket\->insert`                | `Collection\->insert`
|`Bucket\->upsert`                | `Collection\->upsert`
|`Bucket\->replace`               | `Collection\->replace`
|`Bucket\->remove`                | `Collection\->remove`
|`Bucket\->unlock`                | `Collection\->unlock`
|`Bucket\->touch`                 | `Collection\->touch`
|`Bucket\->lookupIn`              | `Collection\->lookupIn`
|`Bucket\->mutateIn`              | `Collection\->mutateIn`
|`Bucket\->counter`               | `BinaryCollection\->increment` and `BinaryCollection\->decrement`
|`Bucket\->append`                | `BinaryCollection\->append`
|`Bucket\->prepend`               | `BinaryCollection\->prepend`
|====

The `BinaryCollection` mentioned above could be retrieved from the regular collection object using the `$collection\->binary()` method.

==== Query

In SDK 3.x, the API for Query was improved and now it is more consistent with other endpoints.

NOTE: In particular, `->rows()` is now a method rather than a property,
and returns an array of fields to index with `['field-name']` instead of
an object with custom property names for each field.

.SDK API 2
[source,php]
----
$query = N1qlQuery::fromString('SELECT airportname FROM `travel-sample` WHERE city=$city AND type=$type');
$query->namedParams(['city' => "Los Angeles", 'type' => "airport"]);
$result = $bucket->query($query);
foreach ($result->rows as $row) {
  printf("%s\n", $row->airportname);
}
----

.SDK API 3
[source,php]
----
$options = new QueryOptions();
$options->namedParameters(['city' => "Los Angeles", 'type' => "airport"]);
$result = $cluster->query('SELECT airportname FROM `travel-sample` WHERE city=$city AND type=$airport', $options);
foreach ($result->rows() as $row) {
  printf("%s\n", $row['airportname']);
}
----

==== Analytics

Analytics queries in SDK API 3 have their own API entry point.

.SDK API 2
[source,php]
----
$query = AnalyticsQuery::fromString('SELECT * FROM dataset WHERE type = $type');
$query->namedParams(['type' => "airport"]);
$result = $bucket->query($query);
foreach ($result->rows as $row) {
  printf("%s\n", $row->airportname);
}
----

.SDK API 3
[source,php]
----
$options = new AnalyticsQueryOptions();
$options->namedParameters(['type' => "airport"]);
$result = $cluster->analyticsQuery('SELECT * FROM dataset WHERE type = $type', $options);
foreach ($result->rows() as $row) {
  printf("%s\n", $row['airportname']);
}
----

==== Search

In SDK API 3, query options and index name has been extracted from the query object.

.SDK API 2
[source,php]
----
$queryPart = SearchQuery::matchPhrase("hop beer");
$query = new SearchQuery("beer-search", $queryPart);
$query->limit(3)->fields("name");

$result = $this->bucket->query($query);
foreach ($result->hits() as $hit) {
  printf("%s - %f\n", $hit->id, $hit->score);
}
----

.SDK API 3
[source,php]
----
$query = new MatchPhraseSearchQuery("hop beer");
$options = new SearchOptions();
$options->limit(3);
$result = $cluster->search("beer-search", $query, $options);
foreach ($result->rows() as $row) {
  printf("%s - %f\n", $row['id'], $row['score']);
}
----

==== Views

The most noticeable change in the Views API for SDK API 3.x is the change of names for consistency control settings.

.SDK API 2
[source,php]
----
$query = ViewQuery::from('design_name', 'test');
$query->consistency(ViewQuery::UPDATE_BEFORE);
$res = $bucket->query($query);
foreach ($res->rows as $row) {
  printf("%s\n", $row->id);
}
----

.SDK API 3
[source,php]
----
$options = new ViewOptions();
$options->scanConsistency(ViewScanConsistency::REQUEST_PLUS);
$res = $bucket->viewQuery('design_name', 'test', $options);
foreach ($res->rows() as $row) {
  printf("%s\n", $row->id());
}
----

=== Batching with Multi Get, Multi Options

This feature of the SDK API 2 is not present in SDK API 3.
See the xref:howtos:concurrent-async-apis.adoc[batching docs] for use of process forks.


== Management APIs

In SDK API 2, the management APIs were centralized in the `ClusterManager` at the cluster level and the `BucketManager` at the bucket level.
Since SDK API 3 provides more management APIs, they have been split up into their respective domains.
For example, when in SDK API 2 you needed to remove a bucket you would call `ClusterManager.removeBucket` -- you will now find it under `BucketManager.dropBucket`.
And, creating a N1QL index now lives in the `QueryIndexManager`, which is accessible through the `Cluster`.

The following tables provide a mapping from the SDK API 2 management APIs to those of SDK API 3:

.`ClusterManager` changes
[options="header"]
|====
| SDK API 2                       | SDK API 3
|`ClusterManager\->info`          | removed
|`ClusterManager\->listBuckets`   | `BucketManager\->getAllBuckets`
|-                                | `BucketManager\->getBucket`
|`ClusterManager\->createBucket`  | `BucketManager\->createBucket`
|`ClusterManager\->removeBucket`  | `BucketManager\->removeBucket`
|`ClusterManager\->upsertUser`    | `UserManager\->upsertUser`
|`ClusterManager\->removeUser`    | `UserManager\->dropUser`
|`ClusterManager\->listUsers`     | `UserManager\->getAllUsers`
|`ClusterManager\->getUser`       | `UserManager\->getUser`
|====

.`BucketManager` changes
[options="header"]
|====
| SDK API 2                                  | SDK API 3
|`BucketManager\->info`                      | removed
|`BucketManager\->flush`                     | `BucketManager\->flushBucket`
|`BucketManager\->listDesignDocuments`       | `ViewIndexManager\->getAllDesignDocuments`
|`BucketManager\->getDesignDocument`         | `ViewIndexManager\->getDesignDocument`
|`BucketManager\->removeDesignDocument`      | `ViewIndexManager\->dropDesignDocument`
|`BucketManager\->insertDesignDocument`      | `ViewIndexManager\->upsertDesignDocument`
|`BucketManager\->upsertDesignDocument`      | `ViewIndexManager\->upsertDesignDocument`
|`BucketManager\->listN1qlIndexes`           | `QueryIndexManager\->getAllIndexes`
|`BucketManager\->createN1qlIndex`           | `QueryIndexManager\->createIndex`
|`BucketManager\->createN1qlPrimaryIndex`    | `QueryIndexManager\->createPrimaryIndex`
|`BucketManager\->dropN1qlIndex`             | `QueryIndexManager\->dropIndex`
|`BucketManager\->dropN1qlPrimaryIndex`      | `QueryIndexManager\->dropPrimaryIndex`
|====


[#sdk4-specifics]
== SDK 4.x specifics

PHP SDK 4.0 implements the SDK API 3 spec, so all the steps above also apply to a migration from a PHP SDK 2.x directly to PHP SDK 4.0.

Additionally, the PHP SDK 4.0 offers a new backend (Couchbase++) with support for 
xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[multi-document ACID transactions],
as well as the capabilities required for upcoming features.
You should be aware of the following considerations arising from this new backend implementation.

The following features are unsupported in 4.0. 
They are available in 3.2, and will be available in a later 4.x release.

* xref:concept-docs:response-time-observability.adoc[Response Time Availability]
* xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions[Legacy durability]
* Log forwarding
* Replica reads

In addition:

* `get` requests on locked documents now retry rather than fast-fail.
* The changes to xref:ref:client-settings.adoc[Client Settings] are not currently documented.
* The changes to xref:howtos:managing-connections.adoc#connection-strings[Connection Strings] are not currently documented.
