= Full Installation
:description: Installation instructions, and download archive for the Couchbase PHP Client.
:page-topic-type: howto
:page-toclevels: 2

// tag::all[]
[abstract]
{description}

For release notes, download links, and installation methods for <<older-releases,earlier releases of the Couchbase PHP Client>>, see below.

include::partial$supported-versions.adoc[]

// include::start-using-sdk.adoc[tag=prep]

// include::start-using-sdk.adoc[tag=install]

== SDK Installation

=== Installing on Mac and Linux systems

Before installing the PHP SDK, the following dependencies must be installed.
We recommend using OS specific utilities such as `brew`, `apt-get`, and similar package management utilities (depending on your environment):

* cmake >= 3.20.0+

* c++ compiler >= std_17

* openssl >= 1.1+


For more details regarding platform support refer to the xref:compatibility.adoc#os-compatibility[Compatibility page].


[IMPORTANT]
====
When installing OpenSSL via `brew install` on *macOS*, the command will not be sufficient to be able to build.
The easiest way to fix this is to add the `OPENSSL_ROOT_DIR` env variable to your exports (e.g., .zshenv). 

[source,console]
----
$ export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
----

If you have any issues setting this up, see the tips mentioned when you run `brew info openssl`.
====

Now, install the Couchbase PHP SDK through your PHP distribution's `pecl` command:

[source,console]
----
$ pecl install couchbase
----

Or install from the Couchbase repository:

[source,console]
----
$ pecl install https://packages.couchbase.com/clients/php/couchbase-4.0.0.tgz
----

Then follow the <<post-installation,post-installation steps>>.

[IMPORTANT]
.New SDK Versions on Old Operating System Versions
====
This SDK runs on top of the {cpp} core, Couchbase{plus}{plus}, which requires a {cpp} 17 compiler, such as GCC 8.0, or more recent versions. 

Older versions of Debian and Ubuntu ship with an older version of GCC -- and RHEL and CentOS also lack a supported version of PHP.
  
Workarounds are available for installing a newer build chain for RHEL and CentOS with https://fedoraproject.org/wiki/EPEL[EPEL^], but this may not be within your company’s policy, so also take a look at container options.
====

==== Alpine Linux

**Alpine Linux** is very slim and uses `musl libc` and the `apk` package manager.
As a result, the installation is a little different from other Unix-Like systems,
and `pecl` equivalent packages are used instead.

Using `apk`, you would install your preferred `php` version, install `libcouchbase`,
and then install the equivalent `pecl` package for the version of `php` that you're using.

[source,console]
----
$ apk add php81
$ apk add php81-pecl-couchbase
----

Then follow the <<post-installation,post-installation steps>>.

=== Installing on Microsoft Windows

Currently there are no pre-built binaries for the Windows platform of PHP SDK 4.x.
Instead, you will need to follow https://github.com/couchbase/couchbase-php-client/blob/4.0.0/WINDOWS.md[these steps] to build an extension along with the PHP interpreter.
This process will be simplified in a future 4.x release where the pre-compiled binaries will be published.

// TODO: Add this back when this is available in a future 4.0.x release
// When using Microsoft Windows, instead of using PECL, download the pre-built binary package matching your environment below.
// You may also download the https://github.com/couchbase/php-couchbase[php-couchbase source code] for the SDK and build it directly in your environment if you have a complete build toolchain.

// Binaries labeled with *(TLS)* are linked against **OpenSSL 1.1.1d (MSVC15)** to support TLS connections to Couchbase.
// Simply download the correct version according to your installation details 
// and then copy the corresponding `libcouchbase.dll` and `php_couchbase.dll` binaries into the `extension_dir` as configured in your `php.ini` configuration.

// Depending on your installation details, you may also have to add the `extension_dir` to your `PATH` variable.

// The packages do not include OpenSSL binaries, 
// therefore they have to be installed in the `PATH` (see https://wiki.openssl.org/index.php/Binaries) for your Windows PHP distribution.

// [source,console]
// ----
// $ copy /b libcouchbase.dll C:\php\ext
// $ copy /b php_couchbase.dll C:\php\ext
// ----

// |===
// |Platform|
// |Source          |https://packages.couchbase.com/clients/php/couchbase-3.2.2.tgz[couchbase-3.2.2.tgz]
// |Checksum        |https://packages.couchbase.com/clients/php/couchbase-3.2.2.sha256sum[couchbase-3.2.2.sha256sum]
// |PHP 7.4 VC15 NTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-7.4-nts-x64.zip[php_couchbase-3.2.2-7.4-nts-x64.zip]
// |PHP 7.4 VC15 ZTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-7.4-zts-x64.zip[php_couchbase-3.2.2-7.4-zts-x64.zip]
// |PHP 8.0 VC16 NTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.0-nts-x64.zip[php_couchbase-3.2.2-8.0-nts-x64.zip]
// |PHP 8.0 VC16 ZTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.0-zts-x64.zip[php_couchbase-3.2.2-8.0-zts-x64.zip]
// |PHP 8.1 VC16 NTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.1-nts-x64.zip[php_couchbase-3.2.2-8.1-nts-x64.zip]
// |PHP 8.1 VC16 ZTS|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.1-zts-x64.zip[php_couchbase-3.2.2-8.1-zts-x64.zip]
// |PHP 7.4 VC15 NTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-7.4-nts-x64-openssl.zip[php_couchbase-3.2.2-7.4-nts-x64-openssl.zip]
// |PHP 7.4 VC15 ZTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-7.4-zts-x64-openssl.zip[php_couchbase-3.2.2-7.4-zts-x64-openssl.zip]
// |PHP 8.0 VC16 NTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.0-nts-x64-openssl.zip[php_couchbase-3.2.2-8.0-nts-x64-openssl.zip]
// |PHP 8.0 VC16 ZTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.0-zts-x64-openssl.zip[php_couchbase-3.2.2-8.0-zts-x64-openssl.zip]
// |PHP 8.1 VC16 NTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.1-nts-x64-openssl.zip[php_couchbase-3.2.2-8.1-nts-x64-openssl.zip]
// |PHP 8.1 VC16 ZTS (TLS)|https://packages.couchbase.com/clients/php/php_couchbase-3.2.2-8.1-zts-x64-openssl.zip[php_couchbase-3.2.2-8.1-zts-x64-openssl.zip]
// |===

// Then follow the post-installation steps.

[#post-installation]
=== Post Installation for All Platforms

Once the PHP SDK has been installed, you need to specify that the PHP interpreter should load the Couchbase PHP SDK as an extension.
To do this:

1. Locate your `php.ini` file.
This can be done using the command `php --ini`
+
[source,console]
----
$ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php/8.1
Loaded Configuration File:         /usr/local/etc/php/8.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/8.1/conf.d
Additional .ini files parsed:      (none)
----
+
2. Insert a line in the `php.ini` file specifying the extension to be loaded; this should be in the `[PHP]` section.
If you don't know where that is, simply search for existing commented or uncommented `extension=` entries in the file.
+
[source,ini]
----
extension=json      ; not needed with PHP 8.0.0+
extension=couchbase
----
+
NOTE: On PHP version 7.2.0 and up, simply using the extension name is preferred.
Previously, you might have used `couchbase.so` or `couchbase.dll`, depending on your platform.

=== PHP Composer

Once the PHP extension is installed, it may be used as any other PHP library through composer as posted at https://packagist.org/packages/couchbase/couchbase[packagist.org].

Ensure that you have installed https://getcomposer.org/doc/00-intro.md[Composer] successfully -- you can verify your installation with:

[source,console]
----
$ composer --version
Composer version 2.3.5 2022-04-13 16:43:00
----

To add Couchbase to your project's dependency list, simply update your `composer.json` file with the following dependencies:

[source,json]
----
"require": {
  ...
  "ext-couchbase": "^4.0",
  "couchbase/couchbase": "^4.0"
}
----

Run `composer update` to lock the change in the generated `composer.lock` file.

=== Note on Extension Dependencies

The Couchbase SDK depends on the https://www.php.net/manual/en/json.installation.php[JSON extension],
which must be loaded before the SDK.
However, it is already included on PHP 8.0.0+ as a core extension.


include::partial$older-releases.adoc[]


// end::all[]
