= Release Notes
:description: Release notes for the Couchbase PHP Client.
:page-topic-type: reference
:page-toclevels: 2
:page-aliases: ROOT:relnotes-php-sdk,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

These pages cover the 4.x versions of the Couchbase PHP SDK.

For download instructions, see the xref:sdk-full-installation.adoc[installation page].



[#latest-release]
== PHP SDK 4.1 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.



=== Version 4.1.5 (21 August 2023)

https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.5[API documentation] | link:++https://github.com/couchbase/couchbase-php-client/compare/4.1.4...4.1.5++[Full Changelog]

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.5.tgz[couchbase-4.1.5.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.5.sha256sum[couchbase-4.1.5.sha256sum]
|===

==== Enhancements

* https://issues.couchbase.com/browse/PCBC-939[PCBC-939]:
Added support for query with Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/118[#118]).

* https://issues.couchbase.com/browse/PCBC-831[PCBC-831]:
Implemented search index management (https://github.com/couchbaselabs/couchbase-cxx-client/pull/115[#115]).

* https://issues.couchbase.com/browse/PCBC-945[PCBC-945]:
Expiry options for increment/decrement are now exposed, as they were before 4.0.0 (https://github.com/couchbaselabs/couchbase-cxx-client/pull/120[#120]).

* https://issues.couchbase.com/browse/PCBC-937[PCBC-937]:
Fixed `removeMulti`, which now correctly removes documents (https://github.com/couchbaselabs/couchbase-cxx-client/pull/123[#123]).

* https://issues.couchbase.com/browse/PCBC-938[PCBC-938]:
Override exception constructor in PHP Extension, which allows to initialize context in derived classes (https://github.com/couchbaselabs/couchbase-cxx-client/pull/117[#117]).

* https://issues.couchbase.com/browse/PCBC-940[PCBC-940]:
Added support for subdoc Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/121[#121]).

* https://issues.couchbase.com/browse/PCBC-884[PCBC-884]:
Added support for Native KV range scans (https://github.com/couchbaselabs/couchbase-cxx-client/pull/122[#122], https://github.com/couchbaselabs/couchbase-cxx-client/pull/127[#127]).

==== Underlying C++ SDK Core

* https://issues.couchbase.com/browse/CXXCBC-333[CXXCBC-333]:
Fixed parsing 'resolv.conf' on Linux (https://github.com/couchbaselabs/couchbase-cxx-client/pull/416[#416]).
** The library might not ignore trailing characters when reading nameserver address from the file.

* https://issues.couchbase.com/browse/CXXCBC-335[CXXCBC-335]:
now logging connection options for visibility (https://github.com/couchbaselabs/couchbase-cxx-client/pull/417[#417]).

* https://issues.couchbase.com/browse/CXXCBC-343[CXXCBC-343]: Continue bootsrap if DNS-SRV resolution fails (https://github.com/couchbaselabs/couchbase-cxx-client/pull/422[#422]).

* https://issues.couchbase.com/browse/CXXCBC-242[CXXCBC-242]:
SDK Support for Native KV Range Scans (https://github.com/couchbaselabs/couchbase-cxx-client/pull/419[#419], https://github.com/couchbaselabs/couchbase-cxx-client/pull/423[#423], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/424[#424], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/426[#426], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/428[#428], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/431[#431], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/432[#432], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/433[#433],  
https://github.com/couchbaselabs/couchbase-cxx-client/pull/434[#434]).

* https://issues.couchbase.com/browse/CXXCBC-339[CXXCBC-339]: Disable older TLS protocols (https://github.com/couchbaselabs/couchbase-cxx-client/pull/418[#418]).


=== Version 4.1.4 (26 May 2023)

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.4

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.4.tgz[couchbase-4.1.4.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.4.sha256sum[couchbase-4.1.4.sha256sum]
|===

==== Enhancements

* Added `couchbase::` namespace to `durability_level`, which fixes using Sync Durability.
(https://github.com/couchbase/couchbase-php-client/pull/102[#102])

* https://issues.couchbase.com/browse/PCBC-934[PCBC-934]:
Fixed setting timeout for transactions.

==== Underlying C++ SDK Core


* https://issues.couchbase.com/browse/CXXCBC-327[CXXCBC-327]:
Bundled Mozilla certificates with the library
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/405[#405],
https://github.com/couchbaselabs/couchbase-cxx-client/pull/408[#408]).
Source: https://curl.se/docs/caextract.html.
Use the `disable_mozilla_ca_certificates` connection string option to disable the bundled certificates.

* https://issues.couchbase.com/browse/CXXCBC-324[CXXCBC-324]:
Port and network name now checked on session restart, improving performance during rebalance
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/401[#401]).

* https://issues.couchbase.com/browse/CXXCBC-323[CXXCBC-323]:
`bootstrap_timeout` and `resolve_timeout` can now be used in the connection string
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/400[#400]).

* Introduced `dump_configuration` option for debugging.
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/398[#398])
It logs cluster configuration at trace level.


=== Version 4.1.3 (13 April 2023)

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.3

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.3.tgz[couchbase-4.1.3.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.3.sha256sum[couchbase-4.1.3.sha256sum]
|===

==== Enhancements

* https://issues.couchbase.com/browse/PCBC-915[PCBC-915]:
Fixed incorrect handling of timestamps as expiry in mutation options
(https://github.com/couchbase/couchbase-php-client/pull/88[#88]).

* https://issues.couchbase.com/browse/PCBC-828[PCBC-828]:
Implemented collection management
(https://github.com/couchbase/couchbase-php-client/pull/89[#89]).

* https://issues.couchbase.com/browse/PCBC-918[PCBC-918]:
Extra attributes in `ExistsResult` (`deleted`, `expiry`, `flags`, and `sequenceNumber`) are now optional
(https://github.com/couchbase/couchbase-php-client/pull/95[#95]).


==== Underlying C++ SDK Core


* https://issues.couchbase.com/browse/CXXCBC-31[CXXCBC-31]:
Allow the use of schemaless connection strings (e.g. `"cb1.example.com,cb2.example.com"`)
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/395[#394]).

* https://issues.couchbase.com/browse/CXXCBC-318[CXXCBC-318]:
Always try TCP if UDP fails in DNS-SRV resolver (https://github.com/couchbaselabs/couchbase-cxx-client/pull/390[#390]).

* https://issues.couchbase.com/browse/CXXCBC-320[CXXCBC-320]:
Negative expiry in atr was leaving docs in a stuck state -- this has been fixed, with expiry atr now becoming an `int32_t`
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/393[#393]).

* https://issues.couchbase.com/browse/CXXCBC-310[CXXCBC-310]:
Improved shutdown of the `LostTxnCleanup` thread
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/389[#389]).


=== Version 4.1.2 (20 March 2023)

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.2

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.2.tgz[couchbase-4.1.2.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.2.sha256sum[couchbase-4.1.2.sha256sum]
|===

==== Enhancements

* https://issues.couchbase.com/browse/PCBC-888[PCBC-888]:
Added new method `Collection#queryIndexes` that allows to manage query indexes defined for the collection
(https://github.com/couchbase/couchbase-php-client/pull/68[#68]).
* Added optional context to `CouchbaseException` constructor (https://github.com/couchbase/couchbase-php-client/pull/85[#85]).

==== Underlying C++ SDK Core

* https://issues.couchbase.com/browse/CXXCBC-144[CXXCBC-144]:
Search query on collections no longer requires you to pass in the scope name -- it is inferred from the index
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/379[#379]).
* https://issues.couchbase.com/browse/CXXCBC-145[CXXCBC-145]:
Search query request, raw option added
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/380[#380]).
* https://issues.couchbase.com/browse/CXXCBC-194[CXXCBC-194]:
The SDK now supports the `ExtThreadSafe` transaction extension
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/374[#374], https://github.com/couchbaselabs/couchbase-cxx-client/pull/376[#376]).
* https://issues.couchbase.com/browse/CXXCBC-316[CXXCBC-316]:
When  a document is removed in a transaction, and then a call made to `get_optional`, we expect to just get an empty optional.
However, the handling was raising a `transaction_operation_failed`
This has been fixed, and an `empty optional` will now be returned
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/385[#385]).
* https://issues.couchbase.com/browse/CXXCBC-310[CXXCBC-310]:
Fixed race condition in transaction_context state machine
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/386[#386], https://github.com/couchbaselabs/couchbase-cxx-client/pull/378[#378]).


=== Version 4.1.1 (22 February 2023)

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.1

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.1.tgz[couchbase-4.1.1.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.1.sha256sum[couchbase-4.1.1.sha256sum]
|===

==== Enhancements

* https://issues.couchbase.com/browse/PCBC-869[PCBC-869]:
  Implemented `changePassword` for management API (https://github.com/couchbase/couchbase-php-client/pull/55[#55],  https://github.com/couchbase/couchbase-php-client/pull/56[#56])
* https://issues.couchbase.com/browse/PCBC-891[PCBC-891]:
  Append extension version info to HELLO indentifier (https://github.com/couchbase/couchbase-php-client/pull/58[#58])
* https://issues.couchbase.com/browse/PCBC-901[PCBC-901]:
  Attach error details to management exceptions (https://github.com/couchbase/couchbase-php-client/pull/71[#71])
* Increase required PHP version up to 8.0 (https://github.com/couchbase/couchbase-php-client/pull/76[#76])

==== Fixes

* https://issues.couchbase.com/browse/PCBC-890[PCBC-890]:
  Scope must implement ScopeInterface (https://github.com/couchbase/couchbase-php-client/pull/57[#57])
* https://issues.couchbase.com/browse/PCBC-899[PCBC-899]:
  Ensure the connection will be closed on error (https://github.com/couchbase/couchbase-php-client/pull/70[#70])
* https://issues.couchbase.com/browse/PCBC-900[PCBC-900]:
  Don't set "function" property on exceptions. (https://github.com/couchbase/couchbase-php-client/pull/74[#74])
* https://issues.couchbase.com/browse/PCBC-905[PCBC-905]:
  Don't dereference empty optional if option is not set (https://github.com/couchbase/couchbase-php-client/pull/75[#75])
* https://issues.couchbase.com/browse/PCBC-907[PCBC-907]:
  Assign meta to view query result (https://github.com/couchbase/couchbase-php-client/pull/79[#79])
* Fix missing header for GCC 13 (https://github.com/couchbase/couchbase-php-client/pull/63[#63])

==== Underlying C++ SDK Core

==== Notable Changes in C++ SDK 1.0.0-dp.4

* https://issues.couchbase.com/browse/CXXCBC-275[CXXCBC-275]:
Update implementation query context fields passed to the server. In future versions of the server versions it will become mandatory to specify context of the statement (bucket, scope and collection).
This change ensures that both future and current server releases supported transparently.
* https://issues.couchbase.com/browse/CXXCBC-296[CXXCBC-296]:
Force PLAIN SASL auth if TLS enabled. Using SCRAM SASL mechanisms over TLS protocol is unnecesary complication, that slows down initial connection bootstrap and potentially limits server ability to improve security and evolve credentials management.
* https://issues.couchbase.com/browse/CXXCBC-295[CXXCBC-295]:
The `get with projections` opration should not fail if one of the the paths is missing in the document, because the semantics is "get the partial document" and not "get individual fields" like in `lookup_in` operation.
* https://issues.couchbase.com/browse/CXXCBC-294[CXXCBC-294]:
In the Public API, if `get` operation requested to return expiry time, zero expiry should not be interpreted as absolute expiry timestamp (zero seconds from UNIX epoch), but rather as absense of the expiry.
* https://issues.couchbase.com/browse/CXXCBC-291[CXXCBC-291]:
Allow to disable mutation tokens for Key/Value mutations (use `enable_mutation_tokens` in connection string).
* Resource management and performance improvements:
** Fix tracer and meter ref-counting (https://github.com/couchbaselabs/couchbase-cxx-client/pull/370[#370])
** Replace `minstd_rand` with `mt19937_64`, as it gives less collisions (https://github.com/couchbaselabs/couchbase-cxx-client/pull/356[#356])
** https://issues.couchbase.com/browse/CXXCBC-285[CXXCBC-285]:
Write to sockets from IO threads, to eliminate potential race conditions. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/348[#348])
** Eliminate looping transform in `mcbp_parser::next` (https://github.com/couchbaselabs/couchbase-cxx-client/pull/347[#347])
** https://issues.couchbase.com/browse/CXXCBC-295[CXXCBC-205]:
Use thread-local UUID generator (https://github.com/couchbaselabs/couchbase-cxx-client/pull/340[#340])
** https://issues.couchbase.com/browse/CXXCBC-293[CXXCBC-293]:
Performance improvements:
*** Speed up UUID serialization to string (https://github.com/couchbaselabs/couchbase-cxx-client/pull/346[#346])
*** Don't allow to copy `mcbp_message` objects (https://github.com/couchbaselabs/couchbase-cxx-client/pull/345[#345])
*** Avoid extra allocation and initialization (https://github.com/couchbaselabs/couchbase-cxx-client/pull/344[#344])
* Build system fixes:
** Fix build with gcc-13 (https://github.com/couchbaselabs/couchbase-cxx-client/pull/372[#372])
** Fix gcc 12 issue (https://github.com/couchbaselabs/couchbase-cxx-client/pull/367[#367])
* Enhancements:
** Include bucketless KV service when ping is requested. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/339[#339])
** Include OS name in SDK identifier (https://github.com/couchbaselabs/couchbase-cxx-client/pull/349[#349])


=== Version 4.1.0 (20 January 2023)

Version 4.1.0 brings a number of improvements related to internal connection behavior.

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.1.0

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.1.0.tgz[couchbase-4.0.0.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.1.0.sha256sum[couchbase-4.0.0.sha256sum]
|===



==== New Features

* https://issues.couchbase.com/browse/PCBC-824[PCBC-824]: Implemented replica reads.
* https://issues.couchbase.com/browse/PCBC-630[PCBC-630]: Implemented legacy durability for mutations (replicateTo/persistTo options)
* https://issues.couchbase.com/browse/PCBC-880[PCBC-880]: Support for configuration profiles

==== Fixes

* https://issues.couchbase.com/browse/PCBC-889[PCBC-889]: Fixed behaviour of 'skip' SearchOption.
* Bug fixes: logger and build improvements


==== Caveats

There are no pre-built binaries for the Windows platform of PHP SDK 4.1.0.
But there are steps in https://github.com/couchbase/couchbase-php-client/blob/4.1.0/WINDOWS.md[WINDOWS.md],
that describe how to build an extension along with PHP interpreter.



== PHP SDK 4.0 Releases

=== Version 4.0.0 (11 May 2022)

Version 4.0.0 is the first major release of the next generation PHP SDK, built on the Couchbase++ library --
featuring multi-document distributed ACID transactions, and bringing a number of improvements related to internal connection behavior.

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.0.0

|===
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.0.0.tgz[couchbase-4.0.0.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.0.0.sha256sum[couchbase-4.0.0.sha256sum]
|===

==== New Features

* https://issues.couchbase.com/browse/PCBC-806[PCBC-806]: Migrated core to Couchbase++.
* https://issues.couchbase.com/browse/PCBC-797[PCBC-797]: Updated the Query Index management API to use scopes and collections.
* https://issues.couchbase.com/browse/PCBC-836[PCBC-836]: Added support for the Transactions API.

==== Caveats

There are no pre-built binaries for the Windows platform of PHP SDK 4.0.0.
But there are steps in https://github.com/couchbase/couchbase-php-client/blob/4.0.0/WINDOWS.md[WINDOWS.md],
that describe how to build an extension along with PHP interpreter.

include::partial$older-releases.adoc[]

// end::all[]
