= Couchbase PHP Release Notes
:description: Release notes for the Couchbase PHP Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-php-sdk,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

These pages cover the 4.x versions of the Couchbase PHP SDK.

For download instructions, see the xref:sdk-full-installation.adoc[installation page].


== Version 4.0.0 (11 May 2022)

Version 4.0.0 is the first major release of the next generation PHP SDK, built on the Couchbase++ library -- featuring
multi-document distributed ACID transactions, and bringing a number of improvements related to internal connection
behavior.

API documentation: https://docs.couchbase.com/sdk-api/couchbase-php-client-4.0.0

|===
|Platform|
|Source          |https://packages.couchbase.com/clients/php/couchbase-4.0.0.tgz[couchbase-4.0.0.tgz]
|Checksum        |https://packages.couchbase.com/clients/php/couchbase-4.0.0.sha256sum[couchbase-4.0.0.sha256sum]
|===

== Caveats

There are no pre-built binaries for Windows platform of PHP SDK 4.0.0. But there are steps in
https://github.com/couchbase/couchbase-php-client/blob/4.0.0/WINDOWS.md[WINDOWS.md], that describe how to build an
extension along with PHP interpreter. Next release will simplify this process and pre-compiled binaries will be
published.

include::partial$older-releases.adoc[]

// end::all[]
