= Couchbase PHP Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-php-sdk

[abstract]
Release notes, installation instructions, and download archive for the Couchbase PHP Client.

// include::start-using-sdk.adoc[tag=prep]

// include::start-using-sdk.adoc[tag=install]

== SDK Installation

=== Installing on Linux-like systems

// needs updating for 3.0

Before installing the PHP SDK, you must install the xref:3.0@c-sdk:hello-world:start-using-sdk.adoc[C SDK -- _libcouchbase_ (LCB)];
version 3.0.0.beta.1 or higher is required from PHP Client 3.0.0beta1.

After installing the C SDK, install the PHP SDK through your PHP distribution's pecl command:

[source,bash]
----
$ pecl install couchbase-3.0.0beta1
----

=== Installing on Microsoft Windows

When using Microsoft Windows, instead of using PECL, download a pre-built binary matching your environment. You may also
download the https://github.com/couchbase/php-couchbase[source] for the SDK and build it directly in your environment if
you have a complete build toolchain.

|===
|Platform|

|PHP 7.1 VC14 NTS|http://packages.couchbase.com/clients/php/php_couchbase-3.0.0beta1-7.1-nts-x64.zip[php_couchbase-3.0.0beta1-7.1-nts-x64.zip]
|PHP 7.1 VC14 ZTS|http://packages.couchbase.com/clients/php/php_couchbase-3.0.0beta1-7.1-zts-x64.zip[php_couchbase-3.0.0beta1-7.1-zts-x64.zip]
|PHP 7.2 VC14 NTS|http://packages.couchbase.com/clients/php/php_couchbase-3.0.0beta1-7.2-nts-x64.zip[php_couchbase-3.0.0beta1-7.2-nts-x64.zip]
|PHP 7.2 VC14 ZTS|http://packages.couchbase.com/clients/php/php_couchbase-3.0.0beta1-7.2-zts-x64.zip[php_couchbase-3.0.0beta1-7.2-zts-x64.zip]
|===


=== Post Installation for All Platforms

Once the PHP SDK has been installed, you need to specify that the PHP interpreter should load the Couchbase SDK as an
extension. To do this:

1. Locate your php.ini file. This can be done using the command `php --ini`
+
[source,bash]
----
 $ php --ini
 Configuration File (php.ini) Path: /usr/local/etc/php/7.2
 Loaded Configuration File:         /usr/local/etc/php/7.2/php.ini
 Scan for additional .ini files in: /usr/local/etc/php/7.2/conf.d
 Additional .ini files parsed:      (none)
----
+
2. Insert a line in the php.ini file specifying the extension to be loaded; this should be in the `[PHP]` section. If
you don't know where that is, simply search for existing commented or uncommented `extension=` entries in the file.
Note that the line differs for Linux/Mac OS from Microsoft Windows.

[source,bash]
----
extension=couchbase.so

extension=couchbase.dll
----

=== Note on Extension Dependencies

The Couchbase SDK depends on the JSON module, therefore it has to be loaded before the SDK.

== Version 3.0.0beta1 (October 23, 2019)

First beta release

* Revised API to conform RFCs and libcouchbase 3.0.0.beta.1

== Version 3.0.0alpha4 (July 18, 2019)

Fourth alpha release

* Removed support of geospatial views
* Implemented analytics query options
* Moved query methods up to cluster level

== Version 3.0.0alpha3 (May 30, 2019)

Third alpha release

* Implemented query options for n1ql
* Implemented query options for views
* Fixed boolean typehint on function signatures
* Implemented subdoc counter spec
* Added delta/initial options for counter operations
* Fixed content property for get operation result
* Fixed parsing integers in operation options
* Relaxed type check on KV mutate value

== Version 3.0.0alpha2 (May 29, 2019)

Second alpha release

* Fixed operation options access
* Fixed build on macos (duplicate symbols error)

== Version 3.0.0alpha1 (May 22, 2019)

First alpha release

* Updated libcouchbase bindings (depends on libcouchbase 3.0.0.alpha.3)
* Support for collections
* Support for sync durability.
