= Document 
:description: Couchbase supports CRUD operations, various data structures, and binary documents.
:nav-title: Documents & Doc Ops
:page-topic-type: concept
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic

[abstract]
{description}

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.


// use the simplicity of https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/read-write.html possibly?
// don't forget https://docs-staging.couchbase.com/dotnet-sdk/2.7/datastructures.html - and Java equiv?

////
== Documents

== Input and Output Types

== Counters

== Data Structures

== Raw Byte Concatenation
////





include::7.1@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,php]
----
upsert(string $id, mixed $value[, UpsertOptions $options = null ]) : MutationResult
insert(string $id, mixed $value[, InsertOptions $options = null ]) : MutationResult
replace(string $id, mixed $value[, ReplaceOptions $options = null ]) : MutationResult
get(string $id[, GetOptions $options = null ]) : GetResult
remove(string $id[, RemoveOptions $options = null ]) : MutationResult
----

include::7.1@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::7.1@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,php,indent=0]
----
include::example$documents-concept.php[tag=mutate-in]
----

or xref:7.1@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `travel-sample`.inventory.airline SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::7.1@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport USE KEYS ["airport_1254"];
----

or

[source,sql]
----
SELECT * FROM `travel-sample`.inventory.airport WHERE META().id = "airport_1254";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,php,indent=0]
----
include::example$documents-concept.php[tag=lookup-in]
----

// Counters

include::7.1@sdk:shared:partial$documents.adoc[tag=counters1]

[source,php,indent=0]
----
include::example$documents-concept.php[tag=counters]
----

include::7.1@sdk:shared:partial$documents.adoc[tag=counters2]

[source,php,indent=0]
----
include::example$documents-concept.php[tag=counter-increment]
----

include::7.1@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `Collection->binary()`.
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters https://docs.couchbase.com/sdk-api/couchbase-php-client/classes/Couchbase-BinaryCollection.html[in the API docs].

// Expiry
include::7.1@sdk:shared:partial$documents.adoc[tag=expiration]


////
include::7.1@sdk:shared:partial$documents.adoc[tag=]


include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]

include::7.1@sdk:shared:partial$documents.adoc[tag=]
////
