= Couchbase PHP SDK 3.2
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase PHP SDK allows you to connect to a Couchbase cluster from PHP.
The Couchbase PHP SDK is a native PHP extension and uses the Couchbase high-performance C library to handle communicating to the cluster over Couchbase binary protocols.


[.column]
[.content]
[source,console]
----
$ pecl install https://packages.couchbase.com/clients/php/couchbase-3.2.0.tgz
----


++++
</div>
++++

[.column]
====== {empty}

== Couchbase PHP SDK 3.2

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
// Try out our xref:sample-application.adoc[Travel Sample Application].
// And take a look at the xref:howtos:working-with-collections.adoc[developer preview of Collections].


[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)];
xref:howtos:n1ql-queries-with-sdk.adoc[Query];
xref:howtos:full-text-searching-with-sdk.adoc[Search];
xref:howtos:analytics-using-sdk.adoc[Analytics];
xref:howtos:view-queries-with-sdk.adoc[Views] --
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://docs.couchbase.com/sdk-api/couchbase-php-client/namespaces/couchbase.html[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
Leverage the new Couchbase Server Scopes and Collection features to build multi-tenant micro-service application.
// Integrate with Open Telemetry API to instrument telemetry data for your mission critical workloads that will make troubleshooting and debugging of your applications easier than ever.
// Add an additional layer of security and protect your sensitive workloads using our Client Side Field Level Encryption capability. 


[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to
xref:project-docs:compatibility.adoc[compatibility tables];
xref:project-docs:sdk-release-notes.adoc[release notes];
xref:project-docs:get-involved.adoc[contribution guide]; and the
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/php-sdk/8[Couchbase forums^].
The PHP SDK can be combined with many other projects in the broader PHP ecosystem and beyond -- in the https://blog.couchbase.com/?s=PHP[Couchbase Blog^] there are several examples.

++++
</div>
++++
