= Install and Start Using the PHP SDK with Couchbase Server
:description: Installing the Couchbase PHP SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-toclevels: 2


include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase PHP SDK allows you to connect to a Couchbase cluster from PHP.
It is a native PHP extension and uses the `Couchbase++` high-performance {cpp} library to handle communicating to the cluster over Couchbase binary protocols.


== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase PHP  SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as the username and password.

[source,php]
----
include::hello-world:example$cloud.php[tags=**]
----

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+ 
-- 
[source,php]
----
include::hello-world:example$start-using.php[tags=**]
----

As well as the PHP SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

== Quick Installation

A more detailed guide in our xref:project-docs:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}]
====
Mac and Linux::
+
--
On Mac and most Linux distributions,
simply use `pecl` to install the Couchbase PHP SDK.

[source,console]
----
$ pecl install https://packages.couchbase.com/clients/php/couchbase-4.0.0.tgz
----
--
Alpine Linux::
+
--
*Alpine Linux* is very slim and uses `musl libc` and the `apk` package manager.
As a result, the installation is a little different from other Unix-Like systems and `pecl` equivalent packages are used instead.

[source,console]
----
$ apk add php7-pecl-couchbase
----
--
Windows::
+
--
Windows downloads and instructions for the PHP SDK are available from xref:project-docs:sdk-full-installation.adoc#installing-on-microsoft-windows[the installation page].
--
====

Make sure to add the extension details to your `php.ini`.
See xref:project-docs:sdk-full-installation.adoc#post-installation[post-installation instructions] for full details:

[source,ini]
----
extension=json      ; not needed with PHP 8.0.0+
extension=couchbase
----

Additionally, if you are using https://getcomposer.org/doc/00-intro.md[Composer], simply update your `composer.json` file with the following dependencies:

[source,json]
----
"require": {
  ...
  "ext-couchbase": "^4.0",
  "couchbase/couchbase": "^4.0"
}
----

And run the `composer update` command.
If there are any problems, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].

== Step-by-step


Start a new project (in VS Code or PhpStorm, etc.) and create a file `cb-test.php`.

Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working with PHP -- e.g. you are evaluating the PHP SDK, but it is not your normal platform.

=== Prerequisites

Install the latest 4.x https://pecl.php.net/package/couchbase[couchbase] SDK package -- see <<quick-install,above>>.

The following code samples assume:

* Couchbase xref:cloud:ROOT:index.adoc[Capella] cluster, or Couchbase Server is installed and accessible locally (xref:server:getting-started:do-a-quick-install.adoc[Do a Quick Install] if you don't already have Couchbase Server installed).

* You have create a bucket (perhaps using the xref:server:manage:manage-settings/install-sample-buckets.adoc[travel-sample dataset], or by creating a new bucket).
Note, the Travel Sample bucket is installed automatically by the Capella free trial

* You have created a Couchbase user named "username" [change as appropriate] with permissions to access the cluster (at least Application Access permissions).

NOTE: Couchbase uses xref:server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.

Firstly, you will need to have a few `import` statements at the top of your PHP program:

[#imports]
[source,php]
----
include::hello-world:example$start-using.php[tag=imports]
----

=== Connection

Then you can connect to the cluster:

[{tabs}] 
====
Capella Connection::
+
--
[source,csharp]
----
include::example$cloud.php[tag=connect,indent=0]
----

From 4.0, the PHP SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases:` in the Connection String as in this example.
--
Local Server Connection::
+
--
[source,php]
----
include::example$start-using.php[tag=connect,indent=0]
----

For developing locally on the same machine as the Couchbase Server, your URI can be _couchbase://localhost_ as here. But for Production deployments, you will want to use a secure server,
with `couchbases://`.
--
====

See xref:howtos:managing-connections.adoc[Managing Connections] for full configuration details.

Couchbase uses xref:server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.


=== Bucket, Scopes, and Collections

Open the bucket:
[source,php]
----
include::example$start-using.php[tag=bucket,indent=0]
----

Collections allow Documents to be grouped by purpose or theme, according to specified _Scope_.
Our Travel Sample bucket has separate scopes for inventory (flights, etc.), and for tenants (different travel agents).

[source,php]
----
include::example$start-using.php[tag=collection,indent=0]
----

To get you started the following code creates a new document in a custom scope and collection and then fetches it again, printing the result.

[source,php]
----
include::example$start-using.php[tag=upsert-get,indent=0]
----

[NOTE]
====
Other possible key/value CRUD Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
====

You can also perform a N1QL query with the cluster object:

[source,php]
----
include::example$start-using.php[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based N1QL language;
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

== Additional Resources

The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-php-client/namespaces/couchbase.html[here^].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating to SDK API 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the PHP SDK.
The PHP SDK source code is available on https://github.com/couchbase/php-couchbase[GitHub].


=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/php-sdk/8[community forum] is a great source of help.
