= Install and Start Using the PHP SDK with Couchbase Server
:description: Installing the Couchbase PHP SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
The Couchbase PHP SDK allows you to connect to a Couchbase cluster from PHP.
It is a native PHP extension and uses the Couchbase high-performance C library to handle communicating to the cluster over Couchbase binary protocols.

== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase PHP  SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
To connect to xref:cloud::index.adoc[Couchbase Capella], be sure to get the correct endpoint as well as user, password, certificate and `couchbasecloudbucket`  -- and see the <<cloud-connections, Cloud section>>, below.

[source,php]
----
include::hello-world:example$cloud.php[tag=cloud_connect]
----
--

Local Couchbase Server::
+ 
-- 
[source,php]
----
$connectionString = "couchbase://localhost";
$options = new \Couchbase\ClusterOptions();
$options->credentials("Administrator", "password");
$cluster = new \Couchbase\Cluster($connectionString, $options);

// get a bucket reference
$bucket = $cluster->bucket("bucket-name");

// get a default collection reference
$collection = $bucket->defaultCollection();

// or for named collection
$collection = $bucket->scope("myapp")->collection("my-collection");

$scope = $bucket->scope("tenant_agent_00");
$collection = $agentScope->collection("users");

// upsert document
$upsertResult = $collection->upsert("my-document", ["name" => "mike"]);

// get document
$getResult = $collection->get("my-document");
----
As well as the Python SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====


== Quick Installation

A more detailed guide in our xref:project-docs:pages:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}]
====
Mac and Linux::
+
--
On Mac and most Linux distributions,
simply use `pecl` to install the Couchbase PHP SDK.

[source,console]
----
$ pecl install https://packages.couchbase.com/clients/php/couchbase-4.0.0.tgz
----
--
Alpine Linux::
+
--
*Alpine Linux* is very slim and uses `musl libc` and the `apk` package manager.
As a result, the installation is a little different from other Unix-Like systems and `pecl` equivalent packages are used instead.

[source,console]
----
$ apk add php7-pecl-couchbase
----
--
Windows::
+
--
Windows downloads and instructions for the PHP SDK are available from xref:project-docs:sdk-full-installation.adoc#installing-on-microsoft-windows[the installation page].
--
====

Refer to the additional details on the xref:project-docs:sdk-release-notes.adoc[Release Notes & Archives page].
In particular, **follow the post-install instructions** according to the `.ini` practices for your platform.
Also notice that the Couchbase PHP SDK depends on the https://www.php.net/manual/en/json.installation.php[JSON extension], 
and it must be loaded before the SDK.


// installation and post-installation across platforms

// end::install[]


== Cloud Connections

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password, and `couchbasecloudbucket`

For developing on Capella, if you are not working from the same _Availability Zone_, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments],
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements],
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].

=== Preamble XXXX

Couchbase uses xref:7.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _localhost_.


=== Connection

[source,php]
----
$connectionString = "couchbase://localhost";
$options = new \Couchbase\ClusterOptions();
$options->credentials("Administrator", "password");
$cluster = new \Couchbase\Cluster($connectionString, $options);
----

The `Cluster` provides access to cluster-level operations like N1QL queries, analytics, or full-text search.
You will also find different management APIs on it.

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

To access the KV (Key/Value) API or to query views, you need to open a `Bucket`:

[source,php]
----
// get a bucket reference
$bucket = $cluster->bucket("bucket-name");
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,php]
----
// get a default collection reference
$collection = $bucket->defaultCollection();

// or for named collection
$collection = $bucket->scope("myapp")->collection("my-collection");
----

The PHP SDK (from version 3.2 onwards) supports full integration with the xref:7.0@server:learn:data:scopes-and-collections.adoc[Collections] feature introduced in Couchbase Server 7.0.
This brings complete support of Collections, allowing Documents to be grouped by purpose or theme, according to a specified Scope.
Here we will use the `users` collection within the `tenant_agent_00` scope from the `travel-sample` bucket as an example.

[source,php]
----
$scope = $bucket->scope("tenant_agent_00");
$collection = $agentScope->collection("users");
----

The code shows how you would use a named collection and scope. A named or default collection will provide the same functionality as bucket-level operations did in previous versions of Couchbase Server.

The `defaultCollection` must be used when connecting to a 6.6 cluster or earlier.
[source,php]
----
// upsert document
$upsertResult = $collection->upsert("my-document", ["name" => "mike"]);

// get document
$getResult = $collection->get("my-document");
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page -- or first see a complete worked example of
using the Couchbase php client, our xref:hello-world:sample-application.adoc[Travel Sample Application].


== Additional Resources

The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-php-client/namespaces/couchbase.html[here^].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating to SDK API 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the PHP SDK.
The PHP SDK source code is available on https://github.com/couchbase/php-couchbase[GitHub].
