= Start Using the PHP SDK
:description: Installing the Couchbase PHP SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:page-toclevels: 2
:page-pagination: full
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase PHP SDK allows you to connect to a Couchbase cluster from PHP.
It is a native PHP extension and uses the `{cbpp}` high-performance {cpp} library to handle communicating to the cluster over Couchbase binary protocols.

In this guide, you will learn:

* How to xref:connect[connect to Couchbase Capella or Couchbase Server].

* How to xref:add-and-retrieve-documents[add and retrieve Documents].

* How to xref:sql-lookup[lookup documents] with the {sqlpp_url}[{sqlpp} (formerly N1QL)] query language.

== Hello Couchbase

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as the username and password.

[source,php]
----
include::hello-world:example$cloud.php[tags=**]
----

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+ 
-- 
[source,php]
----
include::hello-world:example$start-using.php[tags=**]
----

As well as the PHP SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

== Quick Installation

A more detailed guide in our xref:project-docs:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}]
====
Mac and Linux::
+
--
On Mac and most Linux distributions,
simply use `pecl` to install the Couchbase PHP SDK.

[source,console]
----
$ pecl install couchbase
----
--
Alpine Linux::
+
--
*Alpine Linux* is very slim and uses `musl libc` and the `apk` package manager.
As a result, the installation is a little different from other Unix-Like systems and `pecl` equivalent packages are used instead.

// Update usingpage for our SDK inside Alpine Linux: https://pkgs.alpinelinux.org/packages?name=php*-pecl-couchbase&branch=edge 

[source,console]
----
$ apk add php81-pecl-couchbase
----
--
Windows::
+
--
Windows downloads and instructions for the PHP SDK are available from xref:project-docs:sdk-full-installation.adoc#installing-on-microsoft-windows[the installation page].
--
====

Make sure to add the extension details to your `php.ini`.
See xref:project-docs:sdk-full-installation.adoc#post-installation[post-installation instructions] for full details:

[source,ini]
----
extension=couchbase
----

Additionally, if you are using https://getcomposer.org/doc/00-intro.md[Composer], simply update your `composer.json` file with the following dependencies:

[source,json]
----
"require": {
  ...
  "ext-couchbase": "^4.2",
  "couchbase/couchbase": "^4.2"
}
----

And run the `composer update` command.
If there are any problems, refer to the full xref:project-docs:sdk-full-installation.adoc[Installation page].

== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically by the Capella free trial.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started:do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step-by-step

Start a new project (in VS Code or PhpStorm, etc.) and create a file `cb-test.php`.

Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working with PHP -- e.g. you are evaluating the PHP SDK, but it is not your normal platform.

Install the latest 4.x https://pecl.php.net/package/couchbase[couchbase] SDK package -- see <<quick-installation,above>>.

Firstly, you will need to have a few `import` statements at the top of your PHP program:

[#imports]
[source,php]
----
include::hello-world:example$start-using.php[tag=imports]
----

=== Connect

Connect to your cluster by instantiating a new `Cluster` object and pass it your connection details.
The basic connection details that you’ll need are given below -- for more background information, see xref:howtos:managing-connections.adoc[].

[{tabs}] 
====
Couchbase Capella::
+
--
From version 4.0, the PHP SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases://` in the connection string as in this example.

[source,php]
----
include::example$cloud.php[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 4.1 introduces a `wan_development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:php-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Couchbase Server::
+
--
[source,php]
----
include::example$start-using.php[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost` as shown here.
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

Following successful authentication, add this code snippet to access your `Bucket`:

[source,php]
----
include::example$start-using.php[tag=bucket,indent=0]
----

=== Add and Retrieve Documents

Collections allow Documents to be grouped by purpose or theme, according to specified _Scope_.
Our Travel Sample bucket has separate scopes for inventory (flights, etc.), and for tenants (different travel agents).

Here we refer to the `users` collection within the `tenant_agent_00` scope from the Travel Sample bucket as an example, but you may replace this with your own data.

[source,php]
----
include::example$cloud.php[tag=collection,indent=0]
----

xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection->get()` and `Collection->upsert()`.

Add the following code to create a new document and retrieve it:

[source,php]
----
include::example$cloud.php[tag=upsert-get,indent=0]
----

=== {sqlpp} Lookup

Couchbase {sqlpp} queries can be performed at the `Cluster` or `Scope` level by invoking `Cluster->query()` or `Scope->query()`.

Cluster level queries require you to specify the fully qualified keyspace each time (e.g. `travel-sample.inventory.airline`).
However, with a Scope level query you only need to specify the Collection name -- which in this case is `airline`:

[source,php]
----
include::example$cloud.php[tag=n1ql-query,indent=0]
----

You can learn more about {sqlpp} queries on the xref:howtos:n1ql-queries-with-sdk.adoc[] page.

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-php-client/namespaces/couchbase.html[here^].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating to SDK API 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the PHP SDK.
The PHP SDK source code is available on https://github.com/couchbase/php-couchbase[GitHub].


=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/php-sdk/8[community forum] is a great source of help.
